### ISSUE TITLE
Release Ideas !

### ISSUE THREAD

**Issue by Ixoos** [LinxGem33/Arc-Menu#1]
Favorites and recently used tab
Calculator built in search
Gui Option to change menu icon
Gui Option to set the menu on left or right
Gui Option to change the command to run the software center (*I'm not using gnome-software so always when menu is updated i must change it in the menu.js file*)
Gui Option to change icon sizes

I can test this extension and translate it to my language, also from today I decided I will learn better JavaScript so I can help You with developing this extension.

**Comment by LinxGem33** [comment]
@Ixoos 

yeah these are very good ideas and thank you for contributing , ill start testing a coulple of theses ideas i have one problem with the menu that’s the left padding not the inner part of the menu but the outer part of the menu that’s problem no:1 ha.

**Comment by Matt07211** [comment]
Just found out about this from the dash-to-panel extension, I've only just switched to gnome so I'll be setting that up soon. But afterwards I can beta test and report bugs.
But whats the current  progress on this?

**Comment by LinxGem33** [comment]
@Matt07211 

thanks for your interest I’m currently at the alpha stage I’ve got it working on my system but there are a few issues with integration into gnome shell but I’m making progress slowly hence why i need a JavaScript programmer just to take a look at the code and give me a few suggestions  as its not my native programming language, i will almost certainly need testers once i get it stable enough so just add yourself to the project  and hopefully we can get this up and running sooner rather than later.

**Comment by Ixoos** [comment]
I tried to install this extension but error occured :c

**Comment by LinxGem33** [comment]
@Ixoos 

make sure you have gtk 3.18 stack that’s what I’m currently testing on I’m hopefully going to push a somewhat working alpha to the repo soon I’m currently working on the Gnome shell integration then you can play around with the code and see what you find.

regards

**Comment by Ixoos** [comment]
I'm waiting the most for the favorites tab <3 I even made concept for this
http://imgur.com/a/43OvB

**Comment by Matt07211** [comment]
Looks nice. Someone's definitely attached to windows. Hehe. What icon pack was used in mock-up @Ixoos

**Comment by Ixoos** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by Matt07211** [comment]
Thanks for the link

**Comment by LinxGem33** [comment]
@Ixoos 

nice concept I'm thinking about adding the favorites link too.

regards

**Comment by moriel5** [comment]
I only saw your project right now, from the Dash-to-Panel project.
A request: Can you please add an option for the apps to be organized according to A-Z, but without the categories?
And solus-sc is the software manager on Solus, if you wish the menu to show that on Solus.

**Comment by LinxGem33** [comment]
@moriel5 

appreciate the feed back!

ill add your suggestions to the list, however the main target for the first release is to get it working enough for user install on live systems and to submit to gnome extensions.

kind regards

**Comment by moriel5** [comment]
No problem, I can wait.
If there is anything else I can help with, I'll gladly do so (as long as I can fit it within my schedule).

**Comment by LinxGem33** [comment]
First pre alpha  has now been released.

**Comment by Matt07211** [comment]
Yay

**Comment by fishears** [comment]
Really nice project. I just tried it on Ubuntu Gnome 17.04 (Gnome Shell 3.24) and it works very well. I did have to compile the schema xml as there is no gschemas.compiled in /schemas when you pull it from git... maybe add a line on running glib-compile-schemas in the install instructions?

**Comment by LinxGem33** [comment]
@fishears 

appreciate the feed back, i would appreciate it if you could update the changes that you’ve made here on github and contribute your code to this project regarding the compiled schema xml etc, as Im the sole developer of multiple projects and have limited development time, this can be done of course via a pull request at which point i could add you as a collaborator to this project if you so wished.

kind regards

**Comment by LinxGem33** [comment]
@fishears 

I’ve just ran hexdump in terminal to verify the compiled binary code and everything looks ok, i appreciate your contribution thankyou and your more than welcome to contribute in the future if you come across any issues that you feel that you could resolve and would benefit this project and as i said your more than welcome to get involved as a contributor if you feel you want to take a more active role in this project.

kind regards

**Comment by LinxGem33** [comment]
@Ixoos @Matt07211 @moriel5 

v1.0 now released.

you can now start testing this extension let me know if you need advice on how to install also make sure you restart your system once you’ve installed the extension otherwise it may not show up in gnome tweak tool.

kind regards

**Comment by fishears** [comment]
I've made a change on my fork that suits my needs but I don't know if you would want to pull it. It just changes the extension to use the current user's icon theme "start-here-symbolic" icon for the menu. For me it makes the menu look better with different themes but you may disagree ;)
Take a look [here](https://github.com/fishears/Arc-Menu/commit/92af1ffbc620257c13a6369216853a9efd46f1b2) if you like

**Comment by Matt07211** [comment]
@fishears Create a pull request, better to not force a particular icon style onto a user's, which you fix fixes.

@LinxGem33

Dependices? Build commands? Install location? Etc...

**Comment by LinxGem33** [comment]
@fishears 

appreciate the PR, ill take a look at it and test against different versions and see if there i any issues.

kind regards

**Comment by LinxGem33** [comment]
@Matt07211 

I’m going to fill out a installation & sys requirements section on the read me explaining how to install the extension it should be up hopefully by the end of the day again thanks for taking the time to test also remember to state what OS version and distribution your using when leaving feedback regarding testing.

kind regards

**Comment by moriel5** [comment]
This sounds great, I'll be sure to test it when I have the time.
I am not very active lately, simply due to lack of time, and I do read the updates when I can.

**Comment by LinxGem33** [comment]
@Ixoos @Matt07211 @moriel5 @fishears 

I’m pleased to let everyone know that this extension is now officially supported on extensions.gnome.org and you can now install this extension on extensions.gnome.org as a one click install all details are on the extension description page(read.me).

kind regards
