### ISSUE TITLE
Unable to install Arc-Menu

### ISSUE THREAD

**Issue by Creepy12** [LinxGem33/Arc-Menu#100]
Hello, I am having a bit of trouble installing Arc-Menu on my system (I am using Gnome 3.24.2)

When ever I try to install Arc-Menu it turns off after installing it.  Here are some pictures to show what is happening:

I click install
[http://i.imgur.com/kUYjfyi.png](http://i.imgur.com/kUYjfyi.png)

It displays that it is on:
[http://i.imgur.com/9X70GFq.png](http://i.imgur.com/9X70GFq.png)

Then it turns right off:
[http://i.imgur.com/R5kbveo.png](http://i.imgur.com/R5kbveo.png)

I have also tried installing it manually but that dosen't also work either as Gnome Tweak Tool displays unable to load extension.

I also have other extensions on my system and they work just fine put I am not able to install Arc-Menu on my system.

 I would really appreciate your help :)

System information:

Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

GNOME Shell 3.24.2

Logs from systemd journal:

inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/it/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fr/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/vi/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fur/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/sl/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/lv/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/id/LC_MESSAGES/zorinmenu.po
inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/es/LC_MESSAGES/zorinmenu.po
extracting: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/metadata.json

**Comment by lexruee** [comment]
https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's

**Comment by Creepy12** [comment]
@lexruee Hello, I am having a bit of trouble installing Arc-Menu on my system (I am using Gnome 3.24.2)

When ever I try to install Arc-Menu it turns off after installing it. Here are some pictures to show what is happening:

I click install
http://i.imgur.com/kUYjfyi.png

It displays that it is on:
http://i.imgur.com/9X70GFq.png

Then it turns right off:
http://i.imgur.com/R5kbveo.png

I have also tried installing it manually but that dosen't also work either as Gnome Tweak Tool displays unable to load extension.

I also have other extensions on my system and they work just fine put I am not able to install Arc-Menu on my system.

System information: 

Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

GNOME Shell 3.24.2

Logs from systemd journal:

inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/it/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fr/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/vi/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fur/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/sl/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/lv/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/id/LC_MESSAGES/zorinmenu.po
  inflating: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/es/LC_MESSAGES/zorinmenu.po
 extracting: /home/lachlan/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/metadata.json

**Comment by LinxGem33** [comment]
@Creepy12 

appreciate the feed back, have you resolved your issue or are you still having the same issue.

**Comment by Creepy12** [comment]
@LinxGem33 no the issue is still occurring. I have even tried installing it manually but that just give me a error on the gnome tweak tool saying unable to load extension.

**Comment by emjimadhu** [comment]
i have the exact same issue

shell version: 3.20.4
ubuntu version: 16.10

**Comment by lexruee** [comment]
@emjimadhu @Creepy12 
Can you check if `gir1.2-gmenu-3.0` is installed on your system?
For example use the command below:
```
apt list --installed | grep gir1.2-gmenu*
```

**Comment by emjimadhu** [comment]
@lexruee it wasn't installed.. I checked it in devtools as well.. it gave the same error "gmenu not installed".. now I installed gmenu 3.0, after that I can able to install through gnome extensions site.. but after installing the arc menu, I get "error with red button"

_Sent from my ZUK Z1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lexruee** [comment]
@emjimadhu 
Restarting the GNOME Shell does not fix the issue? Command to restart GNOME Shell (might be buggy depending on the amount of installed extensions):
```
Alt + F2 and enter 'r' (without quotes).
```

**Comment by emjimadhu** [comment]
@lexruee nope.. still facing the problem.. I restarted shell and I even restarted the whole system.. I have that same "error" after installing..

_Sent from my ZUK Z1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinxGem33** [comment]
@emjimadhu 

appreciate the feed back, please refer to this issue #81and #84 as i think you maybe missing one more package see below 
```
 sudo apt-get install gir1.2-clutter-1.0 
```
also just to make you aware there is no official support for 17.10 yet as this is still under development and maybe missing features upstream and as a result Arc menu may not work.

kind regards

**Comment by emjimadhu** [comment]
@LinxGem33 it seems i already have the clutter.. this is the message i get when i try to install

"gir1.2-clutter-1.0 is already the newest version (1.26.0-2).
gir1.2-clutter-1.0 set to manually installed."

im not sure what that second line means "set to manually installed"?

**Comment by lexruee** [comment]
@emjimadhu 
It means that you installed gir1.2-clutter-1.0 manually.
I ask again: You are using Ubuntu GNOME?

**Comment by Creepy12** [comment]
I will check all of this stuff after I get home from school

**Comment by Creepy12** [comment]
@lexruee @LinxGem33 I didn't have gir1.2-gmenu-3.0 installed. So I installed it and restated gnome shell. I then went onto extensions.gnome.org and was able to install Arc Menu successfully! :)
![screenshot from 2017-07-26 15-47-50](https://user-images.githubusercontent.com/30363518/28606392-358df9dc-721a-11e7-86d2-c11590a38496.png)

**Comment by lexruee** [comment]
@Creepy12 
Good to hear that this solved your problem. :smiley: 
Short question: Did you install GNOME manually on your Ubuntu system?

**Comment by Creepy12** [comment]
@lexruee do you mean installing it through the terminal? If so, yes I did

**Comment by emjimadhu** [comment]
@lexruee i tried it with my friend's system.. Its not working in there too.. for me atleast i could see settings button next to error button after installation.. but for him, nothing, just the error button..

**Comment by hmksq** [comment]
I am running Ubuntu Gnome 17.10 (dev) and gir1.2-gmenu-3.0 seems to already be installed, yet I am not able to install Arc-Menu. Computer is running Gnome Shell 3.24.3 (from Ubuntu Gnome and not manually installed, Unity is not installed).

``gir1.2-gmenu-3.0/artful,now 3.13.3-6ubuntu5 amd64 [installed]``

I get the same error which everyone is getting (from journalctl). I tried manually installing, and it did not help. The settings button did not appear previously (a month ago when attempting to install), now it appears alongside the error button. I delete the extension from ``~/.local/share/gnome-shell/extensions`` before reinstalling (from extensions.gnome.org and from source), problem persists.

**Comment by lexruee** [comment]
@hmksq @emjimadhu 
I can't really understand why some of the Ubuntu users are always missing some dependencies on their GNOME Desktop, which are usually installed on any sane GNU/Linux Distribution, such as Debian, Fedora, or Arch Linux.

Anyways, I fired up a Ubuntu 17.10 VM with GNOME 3.24 so I could find the issue.
Please install the packages `gnome-tweak-tool` and `gnome-shell-extensions`. Once you have installed them, your system should have all the necessary dependencies.

```
sudo apt install gnome-tweak-tool gnome-shell-extensions
```

After that, try to install the extension again.

**Comment by lestcape** [comment]
@lexruee probably the cannonical team are removing dependencies, maybe because they are trying to create his own vision of gnome >:(

**Comment by lexruee** [comment]
@lestcape
Hi!

I don't know the plans of Ubuntu but honestly I don't care :smile:. I just want to minimize the number of "cannot install" issues.

Anyways, I went to #ubuntu-gnome on chat.freenode.net and told them that they are missing the `gnome-shell-extensions` dependency in their daily iso build, including the ones listed here: https://packages.ubuntu.com/artful/gnome-shell-extensions

So the main question is if the Ubuntu Desktop Team will ship all the GNOME gir dependencies in case they won't ship `gnome-shell-extensions`: https://wiki.ubuntu.com/DesktopTeam/GNOME/MIR_List

**Comment by lestcape** [comment]
@lexruee To be honest, I really can not guess exactly what they want. But apparently they will not want to used the same extensions by default. Is probably better that you list all gnome package that you used, because you will need to do this just one time and if they continues change things you will need to do this several times.

In theory, individual extensions have not a directly way to define dependencies, because they are several in the same package. The container is how have all dependencies that the extension needs. If ubuntu will follow the same criteria of gnome/cinnamon to only included the dependencies that are really needed by the default extensions, then if finally will be added or not a dependency, is the same question more less of what extensions they will want to include by default and this is a thing that not one can answer yet.

**Comment by LinxGem33** [comment]
@hmksq 

appreciate your feed back, just a quick question would you be able to send a Pull Request for a Arabic translation as we currently don’t have a Arabic translation for Arc menu this would be a great help to the team.

all details for a translating guide can be found [here](https://github.com/LinxGem33/Arc-Menu/wiki/Translation-Guide) on Arc menu Wiki.

kind regards - *LinxGem33*

**Comment by navhaxs** [comment]
Since ubuntu noobs like myself are starting to use 17.04, which doesn't have `gir1.2-gmenu-3.0` installed by default, I think future users would appreciate if you add a note to install the package on the readme & gnome extensions site.
