### ISSUE TITLE
Update please extension in extensions.gnome.org

### ISSUE THREAD

**Issue by AlexGluck** [LinxGem33/Arc-Menu#105]
For add translations and managment extension, users check update from site extensions.gnome.org.
Thx for great work.

**Comment by lexruee** [comment]
I think a release v14 in this week should be feasible with the current development branch. But please note it is up to @LinxGem33. He is the benevolent dictator of Arc-Menu :smile:.

On my part, I will try to make some "refactoring" pull requests and a bug-fix pull-request for issue #95. Unfortunately, my spare time is currently very limited, but I will help to test the development branch for the release v14 on my testing systems. 

@AlexGluck you are welcome to test the development branch and report bugs.

**Comment by AlexGluck** [comment]
After done with work and translation other extensions i test devel branch. thx

**Comment by LinxGem33** [comment]
appreciate the feed back once @lexruee has made his final PR and we are happy with v14 :smile:  we will release upstream to extensions.gnome.org also thanks for taking the time to test.

@lexruee  i have been working on the current features we discussed i think im making some progress for v15 :+1: also i PM you i don’t know if you received.

**Comment by lexruee** [comment]
@LinxGem33 Nice!
