### ISSUE TITLE
Version 13 from extensions.gnome.org does not fit on the screen.

### ISSUE THREAD

**Issue by AlexGluck** [LinxGem33/Arc-Menu#106]
Version 13 from extensions.gnome.org does not fit on the screen ![does not fit on the screen](http://i.imgur.com/1biOgpN.png)

**Comment by AlexGluck** [comment]
Add correct EOL. OS fedora workstation 26.

**Comment by lexruee** [comment]
@AlexGluck 
Good catch! We also need to add the GPL2 notice.

**Comment by LinxGem33** [comment]
@AlexGluck  
just re-install the extension in a hour it should be fixed until we update for v14.

**Comment by AlexGluck** [comment]
Tomorrow, now 3:00 am, i go sleep and morning to work.

**Comment by LinxGem33** [comment]
now fixed.
