### ISSUE TITLE
Hold <Super> key.

### ISSUE THREAD

**Issue by AlexGluck** [LinxGem33/Arc-Menu#107]
OS fedora 26 at xorg 
When enable hotkey `<Super>`, all system hotkeys combination with <Super> is holded. 
Such as move window to left and expanded `<Super>+Left`

**Comment by AlexGluck** [comment]
Expected: open menu and auto close if no input activity.

**Comment by AlexGluck** [comment]
Or not steal focus.

**Comment by lexruee** [comment]
Duplicate of issue https://github.com/LinxGem33/Arc-Menu/issues/76.
