### ISSUE TITLE
Better support for high resolution screens

### ISSUE THREAD

**Issue by viktorstrate** [LinxGem33/Arc-Menu#11]
Some of the buttons and icons are out of place. I don't know if it is possible to use som sort of DPI system or similar?

## My setup
Model: Lenovo Yoga 900
OS: Ubuntu Gnome 17.04 zesty
Resolution: 3200x1800

## Screenshot
![screenshot from 2017-05-24 14-14-36](https://cloud.githubusercontent.com/assets/4233458/26402611/5e662246-408b-11e7-9ea8-c416f193da03.png)

**Comment by LinxGem33** [comment]
@viktorstrate 

appreciate the feed back, this issue has been fixed ill be uploading to extensions.gnome.org shortly so keep an eye out for the update.

please see #9 

kind regards
