### ISSUE TITLE
Custom icon on top of Arc icon

### ISSUE THREAD

**Issue by amig** [LinxGem33/Arc-Menu#124]
When I set a custom icon it is display on top the Arc default icon and not instead of it.

**Comment by LinxGem33** [comment]
appreciate the feed back, before we further investigate your issue please could you refer to the wiki guide on [Reporting Bugs](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) as this will give you a guide to what information we require, so we can further investigate your issue.

kind regards

**Comment by amig** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

GNOME Shell 3.18.5

**Comment by LinxGem33** [comment]
we still need the systemd logs.

kind regards

**Comment by amig** [comment]
GNOME Shell started at Wed Aug 09 2017 18:57:55 GMT+0300 (IDT)

**Comment by LinxGem33** [comment]
please follow the reporting bugs guide on how to report bugs as the above is not a proper log, full instructions and the command can be found on the wiki guide link in the previous message.

kind regards

**Comment by amig** [comment]
Sorry but this is all the log I get when running `journalctl /usr/bin/gnome-shell -f -o cat`.

**Comment by lexruee** [comment]
@amig 

0. Which version of Arc-Menu are you using?
1.  Can you provide a screenshot? (Just the drag and drop the file into the comment section)
2. Are you using a custom theme? 
3. Can you give us the output of the program screenfetch or neofetch?
4. Can you post the output of the following command? `dconf dump /org/gnome/shell/extensions/arc-menu/`

Thanks in advance.

**Comment by amig** [comment]
0. 14
1. ![screenshot from 2017-08-10 12-07-04](https://user-images.githubusercontent.com/203434/29163232-81967948-7dc4-11e7-8069-3f107d663146.png)
2. Yes. I'm using Pop custom theme (from system76). I tested with the default theme and there was no issue (i.e., the icon was displayed correctly).
3. [/]
custom-menu-button-icon='/usr/share/icons/Pop/22x22/actions/application-menu.svg'
enable-menu-button-arrow=true
custom-menu-button-icon-size=22.0
menu-button-appearance='Icon'
menu-button-icon='Arc_Menu_Icon'
position-in-panel='Left'

**Comment by lexruee** [comment]
@amig 
As you discovered, this is unfortunately a theme issue of the [pop-gtk-theme](https://github.com/system76/pop-gtk-theme), which is based on the [adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme). In short, this is not a Arc-Menu bug, but rather a feature of the pop-gtk-theme/adapta-gtk-theme.

**Comment by LinxGem33** [comment]
@lexruee  is correct this is a theme specific issue as there is a override in the CSS of the theme you are using it overrides the menu icon and sets its own icon as its based on adapta you may have to alert the creator of the theme of this issue as its not a bug in Arc menu.

kind regards
