### ISSUE TITLE
Packaging (Debian)

### ISSUE THREAD

**Issue by PSSGCSim** [LinxGem33/Arc-Menu#129]
Hello,
does "Awaiting packagers" mean there is an opening for someone willing to host and do packaging? If it is so I am open to creating and hosting Debian repository with package building.

**Comment by lexruee** [comment]
Hi @PSSGCSim fellow Debian user!

In my opinion, that is a great idea since most of the Debian packages will also land in Ubuntu :-). Moreover, we can avoid most of the "Cannot install issues"! I guess @LinxGem33 will also be very happy about this.

**Comment by LinxGem33** [comment]
@PSSGCSim 
appreciate the interest in the Arc menu project we have indeed a opening for a package maintainer we would need the packages signed and also for future development the ability to maintain on launchpad via a PPA as this would integrate nicely with the development cycle of Arc menu, if this is something within your skill set we would be happy to discuss this further with you.

kind regards - *LinxGem33*

**Comment by PSSGCSim** [comment]
@LinxGem33 thank you for fast response. I have been drafting some scripts and I think the Debian repository will be ready in few hours maybe less. I will put them up for your revision soon. Integration with this repository should take few minutes at max.
I never did a Ubuntu PPA repository before. But I can surely look into it. (I am a pretty quick learner) Although, in my opinion it is not needed as the Debian repository is fully compatible with Ubuntu. Most applications supply only one if not explicitly needed.
Only thing I am gonna need to know are required GNOME libraries to run this extension.
To the signing, if you want your own PGP signature it will have to be stored on my servers. I am currently using official public key of my "company".

**Comment by PSSGCSim** [comment]
@LinxGem33 Ok, done. Take a look it should be functional with package in repo for download. https://github.com/PSSGCSim/arc-menu.debian/invitations (private for now)

**Comment by LinxGem33** [comment]
@PSSGCSim 

appreciate the quick set-up everything looks good so far we would need to test, could you also allow access to the repo for @lexruee as he is one of the main developers on the project and if i am not available he would be next in-line to approve changes, also i will give you a list of dependences for Arc menu so you can integrate them into the package set-up (later today after i finish work).

kind regards - *LinxGem33*

**Comment by PSSGCSim** [comment]
Ok @LinxGem33 , I have added @lexruee to the repository. I am planning on making it public but it needs revision first. Also hosting I can provide is 1Gibps server(s) in Germany. I initially setup the builder to run after a new release is added. Repository also contains live link for already built testing packages. So feel free to grab them.
I can fully understand, I will also get around to it again after work too. But now I have full 2 hours of sleep in front of me before my shift. So I am signing of for now. If you or @lexruee think about anything please leave it in comment or you can eventually PM me.

**Comment by LinxGem33** [comment]
will do and thanks again and we will hopefully speak soon.

kind regards

**Comment by LinxGem33** [comment]
@PSSGCSim 
##
The following list should capture the relevant dependencies for Debian testing/Sid and Ubuntu zesty:
##
*Dependencies for Arc menu* 

1. - gir1.2-atk-1.0
2. - gir1.2-clutter-1.0
3. - gir1.2-gdkpixbuf-2.0 
4. - gir1.2-glib-2.0 
5. - gir1.2-gmenu-3.0 
6. - gir1.2-gtk-3.0
7. - gir1.2-pango-1.0 
8. - gnome-tweak-tool
##
*Further information*

if you want to package for a gnome-shell version, i would use something like gnome-shell >= 3.18
this would allow it to work with Debian stretch/testing/Sid and Ubuntu xenial and above also regarding the licence we release everything under a GPLv2 and above hope this is not a issue.
##
kind regards - *LinxGem33*

**Comment by PSSGCSim** [comment]
@LinxGem33 hello, thank you for the information. I will look into it as soon as possible. To the license I have no problems. (the MIT in repo was just a placeholder of a sort)
I think it would be in order to include it under `/usr/doc/gnome-shell-extension-arc-menu/copyright` as it is standard with Debian. If you want more things included like some docs just let me know. It is also possible to include changelogs. If you would want those I think the best way would be to get them from the release info on GitHub.

**Comment by PSSGCSim** [comment]
@LinxGem33 @lexruee I have now published the changes including the license and dependencies. It is up in git and deb repo. It can be now tested. I did not include the `/usr/doc/gnome-shell-extension-arc-menu/copyright` file yet.

**Comment by lexruee** [comment]
@PSSGCSim 
Thanks for your effort and your contributions. Regarding Debian packaging, I should have been more precise (sorry).

Overall, I would strongly prefer to have an official Arc-Menu package in the official Debian repositories with proper gpg signing etc. I know that [Debian packaging](https://wiki.debian.org/Packaging) is really PITA, but in the long-run it is worth the effort to get a Arc-Menu deb package into Debian sid.

Moreover, when we have an official Arc-Menu package in Debian testing/sid, it will possibly also be available in future Ubuntu versions since Ubuntu usually takes packages from Debian sid/testing.

So in the long run an official Arc-Menu package in Debian is my opinion the better approach than a self hosted Debian repository, also in respect to security concerns.

Cheers,
Alex

**Comment by LinxGem33** [comment]
@PSSGCSim 

i must agree with @lexruee that’s what i was under the impression we were doing i.e implementing a package in the official Debian repositories packaged and signed with a key sorry if i wasn’t clear also i also agree with lexuree that i wouldn’t be comfortable hosting Arc menu package externally again if your able to set this up on the official Debian repositories then this would be perfect and again sorry for any confusion.

kind regards - *LinxGem33*

**Comment by lestcape** [comment]
Debian maintainer don't ask. If the licence is pretty clear a free licence then they just add it to a debian repo. Have a debian packages is always good, but not really if is you who need to keep the package and also the develop, because of course gnome is not only for debian and derivate distributions.

Also if you have a debian packages this not mean at all the same package will be installed in ubuntu without a problem. Ubuntu not followed a vainilla gnome instalation. So, nothing will be the same.

**Comment by PSSGCSim** [comment]
@LinxGem33 @lexruee ok, I can fully understand your concerns. - The test repository is removed now. This is why I was not making it public yet.
If you want to go official I would recommend forking other already accepted GNOME extension's packaging repository. I can draft it if you would like me to.

**Comment by PSSGCSim** [comment]
@LinxGem33 @lexruee I would also like to suggest adding the above mentioned dependencies to the main README.md.
And I am sorry about making a fuss with this misunderstanding. Thank you.

**Comment by LinxGem33** [comment]
@PSSGCSim 

no need to apologise the fault was ours for not being clear and sorry for the inconvenience and thank you again for taking the time to contribute we really appreciate it.

kind regards - *LinxGem33*
