### ISSUE TITLE
Request Text Option instead of Icon

### ISSUE THREAD

**Issue by ElectricPrism** [LinxGem33/Arc-Menu#14]
o ) Text "Applications"
o ) Text Label Changable in dconf-editor, etc...

This makes it more consistent if I want to have Places and Recent as my first 3 menus on my Dash to Panel.

Inclusion would be appreciated, wonderful work.

**Comment by LinxGem33** [comment]
@ElectricPrism 

appreciate the feed back, ill add it to the list of feature requests.

kind regards

**Comment by ElectricPrism** [comment]
I went ahead and hacked in the label from the default Gnome Applications extension.

It works just fine if you want to only use the text label and not the icon.

I am unsure how to add entries to the dconf (I'm not sure if I need to compile the schema or what before extension enabling / install, etc... otherwise I would create a true/false toggle)

Looking for feedback and leads to get the patch ship-shape for inclusion

[Arc-Menu-Text-Label-2017-06-18.diff.txt](https://github.com/LinxGem33/Arc-Menu/files/1083612/Arc-Menu-Text-Label-2017-06-18.diff.txt)

**Comment by LinxGem33** [comment]
@ElectricPrism 

appreciate the feed back, yes you need to edit prefs.js schema and then compile with the xml code updated in the schema i think to allow code integration with the extension and also you will need a destructor to allow to enable and disable the code snippet.

kind regards
