### ISSUE TITLE
Menu scrollbar

### ISSUE THREAD

**Issue by AccountOneOff** [LinxGem33/Arc-Menu#144]
Scrollbar is showing up on menu when it's not needed. Using the latest version from Github.

![](https://i.imgur.com/nyCUQPd.png)

**Comment by LinxGem33** [comment]
Please refer to the Wiki section for a guide on: [Reporting Bugs](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's)

**Comment by AccountOneOff** [comment]
Okay I've figured it out. Since I installed `mono-complete` it added the programming menu to the extension. I've since deleted mono and it's hidden the menu as well as the scrollbar. Still though the scrollbar only scrolled a few pixels.

    Ubuntu 17.04
    Gnome-Shell 3.24.2

    $ journalctl /usr/bin/gnome-shell -f -o cat

    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2c00007 specified for 0x2c00005 (albert — A).
    _cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2c00007 specified for 0x2c00005 (albert — A).
    _cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
    Did not find color property '-stipple-color'
