### ISSUE TITLE
Customize menu button appearance won't open

### ISSUE THREAD

**Issue by madaramost** [LinxGem33/Arc-Menu#149]
after click on Customize menu button appearance icon it can't open, is there any dependencies needed to install or what?
<a href="https://imgur.com/GpuAf7B"><img src="https://i.imgur.com/GpuAf7B.png" title="source: imgur.com" /></a>

**Comment by LinxGem33** [comment]
@madaramost 

appreciate the feed back, before we further investigate your issue please could you refer to the wiki guide on [Reporting Bugs](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) as this will give you a guide to what information we require, so we can further investigate your issue.

kind regards

**Comment by madaramost** [comment]
i don't know how but it working now, after running this command:
`$ journalctl /usr/bin/gnome-shell -f -o cat`
and try to change the icon it worked.
thank you very much.
