### ISSUE TITLE
Icons Position Arc

### ISSUE THREAD

**Issue by Aeirex** [LinxGem33/Arc-Menu#15]
![peek 2017-05-27 09-21](https://cloud.githubusercontent.com/assets/1341321/26522086/73c96708-42be-11e7-8e9a-e097ad626572.gif)

![screenshot from 2017-05-27 09-26-34](https://cloud.githubusercontent.com/assets/1341321/26522091/9a35a10e-42be-11e7-8b90-59991dd7b80b.png)

The menu size is too small, it doesn't fit. I have logged out and back in, still seems to be a problem. I don't use OSX-ARC-Shadow due to a color issue with the power buttons and such, but it looks like I have no choice until this is fixed.

It is still a problem with this theme. The size of the menu is too tiny to fit the activities overview. It only works with the Arc White theme, all the other don't work.
![peek 2017-05-27 09-33](https://cloud.githubusercontent.com/assets/1341321/26522165/bad80432-42bf-11e7-9659-beef1295d8d0.gif)

I am using Manjaro Gnome 17.

**Comment by LinxGem33** [comment]
@Aeirex 

appreciate the feed back, this issue has been fixed as well as other issues in v2 of arc menu unfortunately its currently awaiting code review on extensions.gnome.org so please keep an eye out for that.

please see #6 & #9 

kind regards

**Comment by Aeirex** [comment]
@LinxGem33 thanks. I went ahead and reinstalled it using the source. :)

**Comment by LinxGem33** [comment]
@Aeirex 

v3 has now been released with more fixes and is available on extensions.gnome.org.

kind regards
