### ISSUE TITLE
Panel icon wrong size

### ISSUE THREAD

**Issue by tdgroot** [LinxGem33/Arc-Menu#16]
My panel icon looks messed up, something I can do?

![image](https://cloud.githubusercontent.com/assets/1165302/26555046/9d622588-4493-11e7-9501-14395ee4fc48.png)

**Comment by LinxGem33** [comment]
@tdgroot 

either restart your system or log out and back in.

this happens when you first install the extension as the panel hasn’t rendered the image it should be fine once you follow the instructions above.

kind regards

**Comment by tdgroot** [comment]
@LinxGem33 that did the trick, thank you!
