### ISSUE TITLE
Arc Menu doesn't have any support for GNOME 3.26

### ISSUE THREAD

**Issue by Justin00015** [LinxGem33/Arc-Menu#175]

**Comment by lexruee** [comment]
@Justin00015 
As usual, good things need time :-). Basically, the current master branch is already ready for GNOME 3.26. In case you want to be an early adopter, you can install the next release of Arc-Menu from source :-). 

@LinxGem33 will soon push the latest master branch to extensions.gnome.org.

**Comment by Justin00015** [comment]
@lexruee Ok, Great! Just wanted to let you know just to prevent any problems down the line. 😃
