### ISSUE TITLE
problem on make for gnome 3.26

### ISSUE THREAD

**Issue by tsouhaieb** [LinxGem33/Arc-Menu#178]
i cloned the project
and i tried to installed it manualy but error on enable, would you please build it for 3.26

**Comment by LinxGem33** [comment]
appreciate the feed back the issue has now been logged, i shall let @lexruee know regarding this issue as he is maintaining the make script.

**Comment by lexruee** [comment]
@tsouhaieb 
Without extra information, it's difficult to help.  Please have a look at:https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

**Comment by LinxGem33** [comment]
closed due to lack of response.
