### ISSUE TITLE
Use native right click on apps

### ISSUE THREAD

**Issue by rawsh** [LinxGem33/Arc-Menu#180]
Right now, when you right click it launches immediately. Can you add the native right click so options like "New window", "add to favorites", and "launch with discrete graphics card" are available?

**Comment by lexruee** [comment]
@rawsh 
This feature request sounds reasonable ;-).
I assume you mean a right click menu like the one in dash-to-dock or dash-to-panel?

**Example:** Right click menu in Dash-to-Dock
![dash-to-dock-menu](https://user-images.githubusercontent.com/649340/31318941-be1d5598-ac5a-11e7-89d8-b68eb8a92b85.png)

**Comment by rawsh** [comment]
@lexruee Yup!

**Comment by LinxGem33** [comment]
closed due to being a possible planned feature.
