### ISSUE TITLE
Can't enable with Ubuntu 17.04 with Gnome 3.24.2

### ISSUE THREAD

**Issue by Wavum** [LinxGem33/Arc-Menu#181]
I'm using Ubuntu 17.04 with Gnome 3.24.2.
I'm able to install the extension but I'm unable to enable the extension.

### Installed extension
* Dash to dock **(disabled)**
* Dash to panel
* Daynamic top bar **(disabled)**
* Lock keys
* Media player indicator
* No topleft hot corner **(disabled)**
* Sound input & output device chooser
* Status area horizontal spacing
* Top bar script executor
* Topicons plus
* User themes
* Wallpaper changer

**Comment by lexruee** [comment]
@Wavum 
Which Arc-Menu version are you using? Did you try to install it via the extensions.gnome.org website or from source? Can you provide some logs?

For more details see: https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

**Comment by Wavum** [comment]
* I'm using Arc-Menu version 14.
* I tried both.
* Logs via ``journalctl /usr/bin/gnome-shell -f -o cat``:
``
st_widget_get_theme_node called on the widget [0x55f1ac7adb60 StIcon:last-child first-child] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55f1ae8044f0 StIcon:last-child first-child] which is not in the stage.
st_widget_get_theme_node called on the widget [0x55f1ac5eb490 StIcon:last-child first-child] which is not in the stage.
Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
JS WARNING: [resource:///org/gnome/shell/ui/notificationDaemon.js 189]: reference to undefined property ndata.hints['desktop-entry']
JS WARNING: [resource:///org/gnome/shell/ui/notificationDaemon.js 394]: reference to undefined property hints.resident
JS WARNING: [resource:///org/gnome/shell/ui/messageList.js 392]: reference to undefined property this._useBodyMarkup
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000007 (Tilix: Def)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000007 (Tilix: Def)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000007 (Tilix: Def)
``
* I installed gnome from the terminal. I typed ``sudo apt install gdm3``

I've noticed that I only can install Arc-Menu when I disable all extensions (but I'm still unable to use Arc-Menu), when I enable my extension I'm unable to install Arc-Menu.

**Comment by lexruee** [comment]
@Wavum 
You seem to have a broken GNOME desktop right now. You probably forgot to install lot of necessary GNOME dependencies for an usable GNOME Desktop. Overall, we don't support custom Ubuntu installations (see https://github.com/LinxGem33/Arc-Menu/wiki/System-Builds).

Anyways, you can install a minimal, usable GNOME system on Ubuntu zesty (17.04) as follows:
``` 
apt install gnome-shell gnome-shell-extensions gnome-menus nautilus gnome-tweak-tool
```

**Comment by Wavum** [comment]
gnome-shell-extensions was the problem. Somehow it wasn't installed. Thank you very much and nice extension btw :smile:
