### ISSUE TITLE
Allow lock button to work with light-locker for LightDM

### ISSUE THREAD

**Issue by turing-tech** [LinxGem33/Arc-Menu#185]
Right now the lock button only works with gnome window manager. However, running "light-locker-command -l" in a shell would lock the screen for those with the LightDM window manager. If there's a way to detect if light-locker is installed then you could run it then, or you could just include a lightDM compatibility option in the settings.

**Comment by lexruee** [comment]
Currently, the entire code base is being refactored for next release (v16). So I already planned to introduce some kind of an abstraction layer to handle session actions like logout, lock screen etc.
Personally, I don't mind to add lightDM support if it's possible without any dirty hacks etc.

**Comment by LinxGem33** [comment]
closing due to adequate response.
