### ISSUE TITLE
Hitting space in the search bar of the menu acting as the Enter key

### ISSUE THREAD

**Issue by Prototype-00** [LinxGem33/Arc-Menu#186]
For some reason when I search for anything in the menu and hit space it enters the first application by default, what could be the cause of the issue?

**Comment by LinxGem33** [comment]
appreciate the feedback, this issue has now been resolved please see #151 you can either install from source or wait for the new version on extensions.gnome.org it is v15.

**Comment by Prototype-00** [comment]
Oh Beautiful, I think I will wait for the next release, thank you very much for the quick response.
