### ISSUE TITLE
tooltip

### ISSUE THREAD

**Issue by yeKcim** [LinxGem33/Arc-Menu#188]
Add tooltips on icon only buttons Cross, Padlock, Pause, Shutdown

In fact, I'd got to click on the cross and the padlock to be sure of their actions

enhancement

**Comment by lexruee** [comment]
@yeKcim This feature is already planned :-).
See: https://github.com/LinxGem33/Arc-Menu/issues/42 and https://github.com/LinxGem33/Arc-Menu/pull/160

**Comment by yeKcim** [comment]
the github search engine didn't show me these. Thanks lexruee.

duplicate #160 ⇒ close
