### ISSUE TITLE
Click options

### ISSUE THREAD

**Issue by RevTek** [LinxGem33/Arc-Menu#191]
My idea is to add an option to change the functionality of each click type on the Arc-Menu icon.

I find myself missing the activities button, and this would be a good way to allow the functionality of both, along with the possible addition of more functions.

For example:
 Left -> Arc-Menu
 Right -> Activities
 Middle -> Run application

The run application option would also allow custom functionality via scripts.

**Comment by lexruee** [comment]
@RevTek 
Sounds interesting, but this idea could be in conflict with another common functionality, namly a right-click menu with extra options or shortcuts, as shown below:

![right-click](https://user-images.githubusercontent.com/649340/31848057-7f7eee18-b629-11e7-830a-018c13a2d92a.gif)

**Comment by LinxGem33** [comment]
@RevTek  really appreciate the feedback and its a very interesting proposal as @lexruee said in his previous message he is working on a right click feature prototype feature for v16 to work in conjunction with a main feature

re we are currently working on (3) Multi menu although Im open to this kind of work flow in regards to having different functions on the right click i must agree with lexruee we just don’t know if it will conflict with some of the current code base, but i really like the idea of the run application - middle click, i will leave a sneak peek below of the multi menu feature that we are currently working on it has a activities menu option which would act as normal default gnome behaviour and also satisfy all those who like that style as you can understand this has been a massive undertaking to re-factor the code and develop new code alot of which is down to lexruee who has lead this feature forward .
##
i will leave this gif up for a limited time 

![m-chooser](https://user-images.githubusercontent.com/19158615/31850731-645a578c-b64f-11e7-914a-4b7633551fe9.gif)
