### ISSUE TITLE
Space Betweeen App Menu and Fav Apps [Feature Request]

### ISSUE THREAD

**Issue by deepakSP** [LinxGem33/Arc-Menu#192]
It will be great if user can add space between app menu and fav apps !

Edit -
going through all the .js and code, i found out that thr is class (.panel-status-menu-box) assigned to app menu in menuWidget.js so i added margin-right: 1.5em in style sheet.

*Before 
![screenshot from 2017-10-21 18-32-49](https://user-images.githubusercontent.com/11506967/31852024-4ac87e9a-b68e-11e7-90d3-27fb6599f1f9.png)

*After

![screenshot from 2017-10-21 19-22-41](https://user-images.githubusercontent.com/11506967/31852438-43a0bfe0-b695-11e7-858f-5d67fc79cf01.png)

**Comment by LinxGem33** [comment]
appreciate the feedback this issue has now been logged, we shall look into this in a future release hopefully. 

thank you for bringing this to our attention.
