### ISSUE TITLE
TypeError: app is null Ubuntu 17.10

### ISSUE THREAD

**Issue by draekko** [LinxGem33/Arc-Menu#193]
I woke up to the horrors of upgrading to Ubuntu 17.10 this morning. When trying to use the extension i get "TypeError: app is null" (in lg and syslog).

I went back and looked at several closed issues related to 17.10 and made sure gnome-core gnome-shell-extensions gnome-tweak-tool gnome-menus gir1.2-clutter-1.0 gir1.2-gmenu-3.0 were installed. 

I tried installing from through chrome-extensions through my browser (opera and chromium) from https://extensions.gnome.org/extension/1228/arc-menu/ initially but that failed so i installed from a manual install from the cloned repo with the same net result.

Not sure what else i should look at to try to resolve this. 

Thanks in advance :)

**Comment by draekko** [comment]
Addendum i switched to using Xorg from wayland due to issues with xrandr to set up the resolution of my second monitor.

**Comment by lexruee** [comment]
@draekko 
Please have a look at the README. It states the GNOME dependencies that are necessary to install Arc-Menu. Unfortunately, the Ubunti Desktop Team has decided to ship a broken or incomplete GNOME Desktop to their end users. For more details see: https://github.com/LinxGem33/Arc-Menu/issues/189

**Comment by draekko** [comment]
Sigh. I already looked at all the closed issues as well as that one and read the readme. I have already installed the missing packages mentioned in that and other issues. That was the first thing i did. You didn't answer the question. My question was what else can be done to get it working? What else is or could be missing.

**Comment by lexruee** [comment]
> If you want to use a sane GNOME desktop, I would suggest to use Fedora, OpenSuse, Debian, or maybe Antergos. This might sound harsh but Ubuntu 17.10 is just a broken GNOME system.

That's it.

**Comment by LinxGem33** [comment]
@draekko  appreciate the feedback, could you give us  **Logs from the systemd journal**: 

Use the command to log the occurrence of the bug.
```
journalctl /usr/bin/gnome-shell -f -o cat
```

**Comment by draekko** [comment]
Thanks. Here's the output. 

```
Some code accessed the property 'Client' on the module 'dbusMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
[AppIndicatorSupport-DEBUG] Registering StatusNotifierItem org.kde.StatusNotifierItem-9624-2/StatusNotifierItem
Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
gvc_mixer_card_get_index: assertion 'GVC_IS_MIXER_CARD (card)' failed
nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed
Some code accessed the property 'State' on the module 'docking'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [/usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/extension.js 175]: reference to undefined property Symbol.toPrimitive
JS WARNING: [/usr/share/gnome-shell/extensions/disconnect-wifi@kgshank.net/convenience.js 87]: reference to undefined property Symbol.toPrimitive
GNOME Shell started at Sat Oct 21 2017 15:43:46 GMT-0400 (EDT)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x4600007 (GNOME Twea)
```

**Comment by LinxGem33** [comment]
thanks for the logs, as i can see there is nothing pointing to Arc menu rather it seems like a ubuntu issue as you have stated that all dependencies are installed etc, just FYI its not just this extension now that is now having issues with ubuntu 17.10 there are a few now including gnomes default application menu, my advice is log a bug with ubuntu as this would help solve the issues with this new release from ubuntu, i know it may not be what you want to hear but its the best i can offer considering ubuntu has left out alot of dependencies needed to run alot of gnome extensions.

**edit** also as last resort try installing Arc menu from the gnome software store

**Comment by draekko** [comment]
It's been a long time since i've dealt with desktop code/api's and so much has changed lol. Soooooo, What exactly is missing? I have coding experience, i just don't get what's missing from Ubuntu to make it work? 

As for submitting a bug report i know but ugh, i've haven't had good experiences with them on that, and last time i was submitting a kernel patch to fix the issue as well, smh.  Also sadly switching distro's is not likely happen to soon, too much to do right now and too much i can't reinstall right now either :(

Doh, at least i managed to get the desktop somewhat functional after upgrading. Thanks.

**Comment by LinxGem33** [comment]
i really know what you mean its a bit of a headache at the moment with ubuntu 17.10 am sure they will resolve these issues in the near future but as your probably aware the problem is that its usually the 3rd party developers who have to deal with the changes that happen upstream.

i will keep this issue open for a little while just in case we find out what is causing the issues with the gnome extensions at the moment.

also please see below a list regarding what’s included in the development of ubuntu 17.10 maybe this will help you to identify what maybe is missing.

https://wiki.ubuntu.com/DesktopTeam/GNOME/MIR_List

**Comment by draekko** [comment]
Thanks and i do understand, major pita for everyone. Thanks for the link, if i find anything i'll let you know. Not going to be this weekend though as i already wasted too much time trying to get this system working again.

**Comment by draekko** [comment]
I had the chance to upgrade someone elses system to 17.10 and the extension works flawless there. Sadly it still fails on mine. The logs are about as useful as snot in a rag, what would be the best approach to try and debug this (without wiping this machine)?

**Comment by LinxGem33** [comment]
appreciate the update it seems that a  number of people have been experiencing issues with extensions on ubuntu 17.10 due to the way ubuntu has built their gnome system.

> what would be the best approach to try and debug this (without wiping this machine)?

regarding the best approach without making a fresh install, i would suggest opening a virtual machine with a fresh install of ubuntu 17.10 and add arc menu first with all its dependencies then start to add all the packages that you have set up on your host machine one by one, this will actually allow you to find out what is conflicting with arc menu without having to wipe your host machine, i know this is time consuming but it will help you to identify the issue with pin point accuracy.

**Comment by draekko** [comment]
I was hoping there would be some kind of actual debugger (like lldb or gdb for extensions) to figure out what's going. Right now i switched back to applications-menu extension since it works. Will see what else i can dig up when i find some more time.

**Comment by draekko** [comment]
Thanks for closing it, i was going to try debugging the issue but i won't bother now.

**Comment by LinxGem33** [comment]
> i switched back to applications-menu extension since it works

**Comment by lexruee** [comment]
> I was hoping there would be some kind of actual debugger (like lldb or gdb for extensions) to figure out what's going. 

Unfortunately, the most effective way to debug extensions is to monitor the systemd log of the gnome-shell. However, there is also the looking-glass tool: https://wiki.gnome.org/Projects/GnomeShell/LookingGlass

**Comment by lexruee** [comment]
By coincidence, I just came across the error message "TypeError: app is null" on an Arch system.
I think the problem is a missing null check in the if condition here:
https://github.com/LinxGem33/Arc-Menu/blob/master/menu.js#L239

So it seems that sometimes the following lookup code for applications returns a null on some systems:
```
let app = appSys.lookup_app(id);
```

**Comment by draekko** [comment]
@lexruee that fixed it here, and it now works. Thanks.

**Comment by lexruee** [comment]
That's great to hear!

@LinxGem33  I reopen this issue as we need to fix this bug in the master branch as well as in the development branch.

**Comment by LinxGem33** [comment]
@lexruee 

that’s fine, well spotted by the way good job.

**Comment by LinxGem33** [comment]
patch applied.
