### ISSUE TITLE
Search performance is slow

### ISSUE THREAD

**Issue by vanillajonathan** [LinxGem33/Arc-Menu#197]
The type-to-search performance is slow. 😢

**Comment by LinxGem33** [comment]
appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For more details see:
https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

**Comment by vanillajonathan** [comment]
I am not saying it is super slow and takes second to find something. It's just that its not smooth.

When you type in something there is a slight input lag that feels unnatural.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

$ gnome-shell --version
GNOME Shell 3.26.1

$ journalctl /usr/bin/gnome-shell -f -o cat
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
g_signal_handler_disconnect: assertion 'handler_id > 0' failed
^[^C
```

**Comment by LinxGem33** [comment]
hi after further testing i was unable to replicate this issue, im aware every system is uniquely setup differently but i was unable to replicate.

**Comment by LinxGem33** [comment]
closed due to inability to reproduce and also not affecting multiple users.

**Comment by vanillajonathan** [comment]
Maybe could implement some caching?
Or lint the code?
Or see if there is any performance bottlenecks?
I don't know if its possible to do profiling of extensions?
