### ISSUE TITLE
arc menu Error: Type name Gjs_AboutPage is already registered

### ISSUE THREAD

**Issue by niquedegraaff** [LinxGem33/Arc-Menu#199]
I can't activate the extension in a clean Ubuntu 17.10 install + having "Dock to panel" installed because of this error:

`arc menu Error: Type name Gjs_AboutPage is already registered`

**Comment by LinxGem33** [comment]
appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For more details see:
https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information

also if you can make sure you have all the dependencies installed.

https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies

**Comment by niquedegraaff** [comment]
I will try to reproduce as soon as I'm home (in a few days). Thank you.

**Comment by LinxGem33** [comment]
closed this issue due to lack of response.
