### ISSUE TITLE
Tweak Tool Shortcut

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#20]
Hey Andy thanks for this nice extension. Finally, Gnome 3 has a useful menu extension :thumbsup:.

Are there any plans to add a Tweak Tool shortcut to the menu? I forked your repository and implemented this feature for myself in this [repository here](https://github.com/lexruee/Arc-Menu/tree/tweak-tool-shortcut). However, I would like to have this feature in your upstream repository :smiley:.

![arc-menu-with-tweak-tool-shortcut](https://user-images.githubusercontent.com/649340/26861923-927fa338-4b47-11e7-9c36-8e9c6b4e34b4.png)

I assume this feature is missing because in some distributions the gnome-tweak-tool is not shipped with the gnome base package.

**Comment by LinxGem33** [comment]
@lexruee 

appreciate the contribution, your absolutely right that some distributions don’t ship with the tweak tool pre installed however I’ve been debating to add this feature as most distributions will and do now ship with the tweak tool.

regarding applying this feature upstream id be happy to add it just send a pull request and ill add this upstream after testing the code (it looks fine but have to test on a live system ) and thank you so much for taking the time to contribute to this project, once I’ve tested the changes Ill credit your contribution on the main project page and please don’t hesitate to contribute further if you tweak it further and you think it will be useful for the project.

kind regards
