### ISSUE TITLE
Tinkering with dragable desktop launchers for those of us that use icons

### ISSUE THREAD

**Issue by joshuah459** [LinxGem33/Arc-Menu#202]
i was wondering if you guys were planning to make it so that we could drag icons to the desktop for those of us that have it enabled. I was tinkering with it today and was nearly successful in getting it working by splicing it with the applications menu from gnome 3.24. Anyway its just a question because that would make your menu pretty much perfect for me :) thanks in advance! I managed to integrate the desktop target and and its calls throughout the extension, but still couldn't get it to actually drop it would just drag and hold lol.  .. anyway just was wondering if you guys had given the idea any thoughts. 

This is the large segment of code i found from 3.24:
> const DesktopTarget = new Lang.Class({
    Name: 'DesktopTarget',

    _init: function() {
        this._desktop = null;
        this._desktopDestroyedId = 0;

        this._windowAddedId =
            global.window_group.connect('actor-added',
                                        Lang.bind(this, this._onWindowAdded));

        global.get_window_actors().forEach(a => {
            this._onWindowAdded(a.get_parent(), a);
        });
    },

    get hasDesktop() {
        return this._desktop != null;
    },

    _onWindowAdded: function(group, actor) {
        if (!(actor instanceof Meta.WindowActor))
            return;

        if (actor.meta_window.get_window_type() == Meta.WindowType.DESKTOP)
            this._setDesktop(actor);
    },

    _setDesktop: function(desktop) {
        if (this._desktop) {
            this._desktop.disconnect(this._desktopDestroyedId);
            this._desktopDestroyedId = 0;

            delete this._desktop._delegate;
        }

        this._desktop = desktop;
        this.emit('desktop-changed');

        if (this._desktop) {
            this._desktopDestroyedId = this._desktop.connect('destroy', () => {
                this._setDesktop(null);
            });
            this._desktop._delegate = this;
        }
    },

    _getSourceAppInfo: function(source) {
        if (!(source instanceof ApplicationMenuItem))
            return null;
        return source._app.app_info;
    },

    _touchFile: function(file) {
        let queryFlags = Gio.FileQueryInfoFlags.NONE;
        let ioPriority = GLib.PRIORITY_DEFAULT;

        let info = new Gio.FileInfo();
        info.set_attribute_uint64(Gio.FILE_ATTRIBUTE_TIME_ACCESS,
                                  GLib.get_real_time());
        file.set_attributes_async (info, queryFlags, ioPriority, null,
            (o, res) => {
                try {
                    o.set_attributes_finish(res);
                } catch(e) {
                    log('Failed to update access time: ' + e.message);
                }
            });
    },

    _markTrusted: function(file) {
        let modeAttr = Gio.FILE_ATTRIBUTE_UNIX_MODE;
        let trustedAttr = 'metadata::trusted';
        let queryFlags = Gio.FileQueryInfoFlags.NONE;
        let ioPriority = GLib.PRIORITY_DEFAULT;

        file.query_info_async(modeAttr, queryFlags, ioPriority, null,
            (o, res) => {
                try {
                    let info = o.query_info_finish(res);
                    let mode = info.get_attribute_uint32(modeAttr) | 0100;

                    info.set_attribute_uint32(modeAttr, mode);
                    info.set_attribute_string(trustedAttr, 'yes');
                    file.set_attributes_async (info, queryFlags, ioPriority, null,
                        (o, res) => {
                            o.set_attributes_finish(res);

                            // Hack: force nautilus to reload file info
                            this._touchFile(file);
                        });
                } catch(e) {
                    log('Failed to mark file as trusted: ' + e.message);
                }
            });
    },

    destroy: function() {
        if (this._windowAddedId)
            global.window_group.disconnect(this._windowAddedId);
        this._windowAddedId = 0;

        this._setDesktop(null);
    },

    handleDragOver: function(source, actor, x, y, time) {
        let appInfo = this._getSourceAppInfo(source);
        if (!appInfo)
            return DND.DragMotionResult.CONTINUE;

        return DND.DragMotionResult.COPY_DROP;
    },

    acceptDrop: function(source, actor, x, y, time) {
        let appInfo = this._getSourceAppInfo(source);
        if (!appInfo)
            return false;

        this.emit('app-dropped');

        let desktop = GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DESKTOP);

        let src = Gio.File.new_for_path(appInfo.get_filename());
        let dst = Gio.File.new_for_path(GLib.build_filenamev([desktop, src.get_basename()]));

        try {
            // copy_async() isn't introspectable :-(
            src.copy(dst, Gio.FileCopyFlags.OVERWRITE, null, null);
            this._markTrusted(dst);
        } catch(e) {
            log('Failed to copy to desktop: ' + e.message);
        }

        return true;
    }
});
Signals.addSignalMethods(DesktopTarget.prototype);

**Comment by LinxGem33** [comment]
appreciate the feed back we currently have a drag and drop feature which integrates with dash to panel but if you feel that you can add to this feature your more that welcome to send a pull request for review by one of the arc menu team regarding this feature but at the moment its not something with a high priority for development  but we will defiantly log this issue for future reference.

kind regards
