### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by morealaz** [LinxGem33/Arc-Menu#206]
Hi, I just create a package in AUR for installing Arc menu extension for Arch users.
https://aur.archlinux.org/packages/gnome-shell-extension-arc-menu-git/

**Comment by LinxGem33** [comment]
appreciate the contribution to the project thank you, i will leave this issue open till more people can test the AUR package once its been tested would you be able to maintain the package for the AUR?

**Comment by morealaz** [comment]
Yes, I will maintain package.

**Comment by traschke** [comment]
I installed the package yesterday and everything works just fine.
