### ISSUE TITLE
Customizable window height

### ISSUE THREAD

**Issue by AlexWayfer** [LinxGem33/Arc-Menu#207]
Hello!

I have a relatively small number of categories in the menu, but one and a half of them are hidden. And I was very upset to find that I can't increase the height of the window, although the dimensions of my monitor allow me to do this.

![image](https://user-images.githubusercontent.com/6510020/33795817-9f979df2-dcf9-11e7-9f42-58ec708da349.png)

Thank you!

**Comment by LinxGem33** [comment]
hi appreciate the feedback, this is actually one of the planned features for Arc menu please see the development roadmap below.

https://github.com/LinxGem33/Arc-Menu/issues/42

**Comment by AlexWayfer** [comment]
@LinxGem33, thank you! Sorry for inattention. I will follow the roadmap!
