### ISSUE TITLE
Conflict with some status bar extensions

### ISSUE THREAD

**Issue by Adzetko** [LinxGem33/Arc-Menu#208]
I've recently posted an issue on the Unite-shell extension GitHub (there: https://github.com/hardpixel/unite-shell/issues/25 on the screenshots you don't see the Arc Menu button because I sat it on the right) about having the window buttons not in the place it is meant to be. This plugin merge a window title bar with the status bar when maximized, and there is an option to place the buttons on the left or right of the bar, but actually, if I disable Arc-menu, this will correct the bug.
Also, I've tried Pixel-saver (here https://extensions.gnome.org/extension/723/pixel-saver/ ) which is basically doing the same thing (but Unite-shell has other features too) and the conflict is also there when I try to use it with Arc-menu.
Ialso tried No-Title-Bar (here:https://extensions.gnome.org/extension/1267/no-title-bar/ ) with same results.

**Comment by LinxGem33** [comment]
appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For more details see:
[Supporting Information](https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information)

also if you can make sure you have all the dependencies installed:
[Gnome Dependencies](https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies)

kind regards

**Comment by LinxGem33** [comment]
closed due to lack of response.
