### ISSUE TITLE
got error when installing on gnome 3.26.1

### ISSUE THREAD

**Issue by MetaiR** [LinxGem33/Arc-Menu#211]
hello, I got an error when I tried to enable(install) it on my linux which is running gnome 3.26.1 on OpenSUSE os

what should I do?

**Comment by pprok** [comment]
try this `zypper in typelib-1_0-GMenu-3_0`

**Comment by LinxGem33** [comment]
Before logging information for this bug report please make sure that you first make sure that these packages are installed as Arc menu depends on them.

```
zypper in typelib-1_0-GMenu-3_0
```

appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For the information we need please see:
[Supporting Information](https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information)

also if you can make sure you have all the dependencies installed:
[Gnome Dependencies](https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies)

kind regards

**Comment by LinxGem33** [comment]
i am going to close this issue as there has been no response from user.
