### ISSUE TITLE
Sub directories in the menu

### ISSUE THREAD

**Issue by dln949** [LinxGem33/Arc-Menu#214]
Ubuntu 17.10 (x11), gnome 3.26.2, recently installed arc menu.  

Using version 2.1.3 of Menu Libre, I created some directories and subdirectories with launchers in them.  To my surprise, using Arc Menu I can see/expand only the top level directories.  Is that a bug?  Thanks.

**Comment by LinxGem33** [comment]
hi appreciate the feed back is it possible for you to post a screen capture of what you mean as i have used menu libre on multiple occasions with arc menu without issue.

**Comment by dln949** [comment]
Yes, please look at the attached three screenshots.  #1 shows in Menu Libre that I have a top level directory called "Default".  Within it I have a subdirectory called "Demo", and within that I have one launcher for gedit.  

Screenshot #2 shows what I see when I first click on Arc Menu.  You can see the top level directory of "Default".  

Screenshot #3 shows what I see when I click on the top level directory of "Default":  It shows all the launchers, including the launcher for gedit that is in the subdirectory of "Demo", but it does not show the subdirectory of "Demo".  

![screenshot1](https://user-images.githubusercontent.com/8601150/35495563-1020f884-0487-11e8-8b81-b5f660f671bf.jpg)
![screenshot2](https://user-images.githubusercontent.com/8601150/35495564-1040c646-0487-11e8-8f9a-bdf2eece2874.jpg)
![screenshot3](https://user-images.githubusercontent.com/8601150/35495565-104f083c-0487-11e8-8cb8-5d137fc6d8b8.jpg)

**Comment by LinxGem33** [comment]
ahhh i understand what you mean now.

this is normal behaviour as arc menu is a category based application menu meaning top level would be internet, office, system tools etc and to achieve what you want to do you would edit the categories part as it would only go down one level and you have three levels TOP > CAT > LAUNCHER . how arc menu would display is TOP > (CAT + LAUNCHER)
##
schema code for hierarchy of menu

```xml
<enum id='org.gnome.shell.extensions.arc-menu.visible'>
    <value value='0' nick='ALL'/>
    <value value='1' nick='APPS_ONLY'/>
<value value='2' nick='SYSTEM_ONLY'/>
```
##
menulibre category options 

![mex](https://user-images.githubusercontent.com/19158615/35495914-684cff10-04bb-11e8-939e-7161b830bc1c.png)

**Comment by dln949** [comment]
ok, thanks.
