### ISSUE TITLE
Arc-menu uses Ubuntu font, instead of font chosen in Gnome Tweak tool

### ISSUE THREAD

**Issue by wojciechrak** [LinxGem33/Arc-Menu#216]
In Gnome Tweak tool, I've chose "Myriad Set Pro Medium" as my font for everything (except monospace).
![image](https://user-images.githubusercontent.com/3034230/35874079-d8aa16e2-0b6b-11e8-9bd3-2e74f971d249.png)

However the Arc menu still uses Ubuntu font
![image](https://user-images.githubusercontent.com/3034230/35874262-5919cdae-0b6c-11e8-8e39-55f9d2aa62ba.png)

How can I change to font on Arc menu?

**Comment by LinxGem33** [comment]
hi appreciate the feed back, to answer your question Arc menu inherits the shell font so either your theme will set the shell font or you can set the shell font by editing the gnome-shell css file i will leave an example below so you know where it is in the file.

[Example](https://github.com/LinxGem33/OSX-Arc-White/blob/master/gnome-shell/gnome-shell.css#L10)

kind regards
