### ISSUE TITLE
Shortcut for opening the trash folder

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#22]
@LinxGem33 What do you think about a shortcut for opening the trash folder? Do you think this would be useful? Here is a screenshot of a modified Arc Menu with a Trash shortcut.

![arc-menu-with-trash-bin](https://user-images.githubusercontent.com/649340/26872455-dd3adc9c-4b76-11e7-9feb-15bbf8593013.png)

**Comment by LinxGem33** [comment]
@lexruee 

yeah i think that would be useful, just send a pull request and ill add the changes upstream, and thank you again for taking the time to contribute.

kind regards

**Comment by lexruee** [comment]
No problem :-). I can tell you this extension will be a popular one for future Gnome users :smiley: .

**Comment by LinxGem33** [comment]
i definitively agree with you it helps people who are coming from windows to feel more at ease with using gnome.

i only have one problem at the moment and thats trying to bind the menu to the super key

```javascript
this._action = global.display.grab_accelerator('<Super>t');
if (this._action == Meta.KeyBindingAction.NONE)
    return;
Main.wm.allowKeybinding(Meta.external_binding_name_for_action(this._action),
                        Shell.ActionMode.NORMAL);
```


This works in some cases but the same for the overlay-key. so, i don’t know if this is at the same point again. to have a global key-binding, it needs work with Gio.Settings.

**Comment by lestcape** [comment]
@LinxGem33 The Menu manager have a grabber https://github.com/GNOME/gnome-shell/blob/master/js/ui/popupMenu.js#L1216. The gnome shell grabber have a filter https://github.com/GNOME/gnome-shell/blob/master/js/ui/grabHelper.js#L277  that not allow to trespass some events. This is why is not working always.
