### ISSUE TITLE
the po file of the simple Chinese translation

### ISSUE THREAD

**Issue by weearc** [LinxGem33/Arc-Menu#221]
I'd like to post the Chinese translation and have uploaded it
[zh_CN.zip](https://github.com/LinxGem33/Arc-Menu/files/1771915/zh_CN.zip)
May it do a lot of help to the Chinese lover for the extansion

**Comment by LinxGem33** [comment]
thank you for contributing, can you please send the translation via a pull request as this is how we work on the project.
