### ISSUE TITLE
Arc menu breaks Super+key combinations

### ISSUE THREAD

**Issue by chromevanadium** [LinxGem33/Arc-Menu#225]
Arc menu currently appears when the Super key is pressed, not when it is pressed and released. This way, it breaks other Super+key bindings such as Super+h to hide a window or Super+l to lock: each time, Arc will appear. The "normal" behaviour would be to have Arc appear only when the Super key is pressed and released.

That is why I tried to use ksuperkey instead to mimic that behaviour. ksuperkey maps a press and quick release of Super to a hotkey of choice (by default Alt+F1). This requires disabling org.gnome.mutter overlay-key. However, I noticed that arc appears to aggressively set org.gnome.desktop.wm.keybindings panel-main-menu and org.gnome.mutter overlay-key on its own. One would e.g. want to bind Arc to Super+x, and disable Super altogether by setting org.gnome.mutter overlay-key to an empty string. Yet, irrespective of any Arc settings, it sets that key to 'Super_L'.

Suggestion: Arc should only touch these dconf keys if required to enable a "hotkey option" (Super_L or Super_R). Otherwise, it should leave these dconf keys alone.

**Comment by LinxGem33** [comment]
duplicate #76
