### ISSUE TITLE
GNOME error loading extension

### ISSUE THREAD

**Issue by jonalencar** [LinxGem33/Arc-Menu#227]
Hi, I tried installing Arc-Menu with [this package](aur.archlinux.org/packages/gnome-shell-extension-arc-menu-git/) after a fresh install of Arch Linux. However, when I go up to enable it in GNOME tweaks, I encounter an error. When I hover over it says "Error loading extension".
![image](https://user-images.githubusercontent.com/20737987/39355857-3a50e57a-49c3-11e8-9d98-7b65d656bb7f.png)

After further investigation by running 
`sudo journalctl /usr/bin/gnome-shell`

I found this error occurs at login
`Extension "arc-menu@linxgem33.com" had error: Error: Requiring GMenu, version none: Failed to load typelib file '/usr/lib/girepository-1.0/GMenu-3.0.typelib' for namespace 'GMenu': The specified typelib length 0 is too short`

I tried searching around and installing gnome-menus but this did not fix it.
Any ideas?

**Comment by LinxGem33** [comment]
hi appreciate the feedback, it should be working on Arch ive tested it personally and it just needed the 'gnome-menus' package, you also have to realise that arch is a rolling release distro and as such packages are continually updated which will always allow for packages to break compatibility with other packages, as well as the 'gnome-menus' package there is also another dependency which is required called 'gir1.2-gmenu-3.0' which is a Ubuntu package which im not not sure what the equivalent is in Arch.

kind regards

**Comment by jonalencar** [comment]
I fixed the issue by reinstalling arch. Initially I had installed this extension before installing gnome-menus which seems had corrupted gnome-menus in some way.

**Comment by LinxGem33** [comment]
I'm glad you managed to fix the issue thanks for letting me know.
