### ISSUE TITLE
Add Shortcut to side panel at user request.

### ISSUE THREAD

**Issue by lestcape** [LinxGem33/Arc-Menu#28]
This is implemented inside Configurable Menu (a menu that run inside Cinnamon).
https://github.com/lestcape/Configurable-Menu

Proposed mechanism, by steps:
1- Create customs menu items that are not included directly inside the GMenu model, they are places always, like trash and more, so add it to a menu places category.
2- Create a sub-menu for all menu-items with an option to add the item to the panel or remove the item from the panel if was added.
3- Create two gsettings list to set there the application id for applications or the uri for places.
4- The side panel will be build base on this two list, The action of the menu items will add/remove the id from the list.

In that way user can defined his on side panel items and you can set by default in the list, most commons menu items.

**Comment by LinxGem33** [comment]
@lestcape 

it looks really good but would you be able to integrate into arc menu as you know my knowledge is limited as I’m still learning gnome shell and gtk based coding languages.

kind regards

**Comment by lestcape** [comment]
Yes, but i see how there are several people making contributions to your menu. So, maybe other could add this two, and not one need to way for that.

**Comment by lexruee** [comment]
@LinxGem33 
I'm also a Gnome Shell Rookie but I am eager to learn this stuff. I guess you already know the Un-official JavaScript Api Documentation here: https://www.roojs.com/seed/gir-1.2-gtk-3.0/gjs/index.html
I'm currently reading the source code of some extension in order to have a better understanding of the "gnome shell framework".

**Comment by LinxGem33** [comment]
@lexruee 

thank you for the link to the JavaScript API documentation, i have learned a lot just by looking at the source code of other extensions as well it took me three months just to port this extension as i had zero knowledge of JavaScript etc, i now want to create a prefs.js file for the menu and its going slowly but if you want to help each other that would be cool as you could give me pointers and visa versa as the say two heads are better than one.

kind regards
