### ISSUE TITLE
Menu Icon and Modal Style Not Loading Properly

### ISSUE THREAD

**Issue by flycal6** [LinxGem33/Arc-Menu#30]
Often the icon loads too big as seen in the attached image.  The modal attachment is also different, as seen.  Maybe my theme is overriding styling (Paper theme)?

Sometimes, the icon reverts to the correct, smaller size on it's own, and sometimes it stays large.  I haven't noticed any pattern to when it changes.

Gnome 3.24 wayland

![arc-menu](https://user-images.githubusercontent.com/7415126/27173943-f886e5ac-51c2-11e7-8b10-dc99e0a79d89.png)

**Comment by LinxGem33** [comment]
@flycal6 

appreciate the feed back it has now been fixed in a recent PR update #25 it now uses the symbolic icon instead of a dedicated icon I’m just waiting for the extension to be approved on extensions.gnome.org.

kind regards
