### ISSUE TITLE
I can't install on Debian Stretch

### ISSUE THREAD

**Issue by superlativo77** [LinxGem33/Arc-Menu#31]
Hi. Great work. Arc-Menu is the most cool menu app on Gnome. 

I can't install on Debian Stretch with Dash to panel extension? I tried with one click and manually but doesn't work. Even after rebooting. 

Any idea? 

Thanks in advance.

**Comment by lexruee** [comment]
@superlativo77 
Indeed, Arc Menu is a cool looking Gnome Menu ;-).

I've tested Arc Menu on a pure Debian Stretch System using Virtualbox. For installing Arc Menu I used the firefox-esr browser and the one-click install. I also installed the extension Dash-to-Panel. On my virtual machine everything seems to work.

![vanilla_debain_stretch](https://user-images.githubusercontent.com/649340/27292053-6ea6c958-5512-11e7-8653-4d5cefccb56e.png)

**Comment by LinxGem33** [comment]
@superlativo77 

as i haven’t tested against Debian stretch i cant really advise but some users have stated that having the Custom Corner extension activated has conflicts with this extension so maybe try and disable this extension if its enabled other than that i don’t know what to suggest as @lexruee  has stated its working on the same system set-up.

kind regards

**Comment by superlativo77** [comment]
Thanks guys. I have official Firefox 54 and I don't use CustomCorner extension. When I press the button in Gnome extensions website the extension download it and install it but the ON button switch to OFF.
Also I installed manually and restart it the OS but doesn't work.
I don't know which is the problem.

**Comment by superlativo77** [comment]
I tried with Chromium and neither. When I press button the extension is downloaded and installed but in a few seconds the button switch to OFF.
I installed Firefox ESR and the button remains active in ON position but the extension don't appear in Tweak Tool. I rebooted the machine but neither.

: (

**Comment by LinxGem33** [comment]
could everybody now test by manually installing from the main branch as i believe the fix has been found for the issue following testing.

kind regards

**Comment by LinxGem33** [comment]
fix now posted please see a33eee8

kind regards
