### ISSUE TITLE
Error Installing Extension

### ISSUE THREAD

**Issue by flycal6** [LinxGem33/Arc-Menu#33]
Doesn't install.  After the popup asking to install, it switches back to 'off' and doesn't install.

Tried running `journalctl /usr/bin/gnome-session -f -o cat` , but no error messages came up.

**Comment by LinxGem33** [comment]
@flycal6 

appreciate the feed back, I’ve just tested arc menu on gnome 3.18 to 3.24 everything works up until 3.24 which would be 17.04 which is what i presume your using as you have not given me details about your set up i can not find any error messages the code is pretty clean as far as i can see which leads me to believe its not an issue with arc menu rather an issue with 17.04 gnome shell 3.24  its a conflict that I’m unable to pin point at this moment but the extension has been reviewed by extensions.gnome.org and one of the things tested is conflicts with different shell versions so at this point I’m even confused as to what the issue may be.

kind regards

**Comment by flycal6** [comment]
Sorry, I should've included setup details.  
This is on gnome-shell 3.24.2 on Arch.  Could be a conflict with another extension, as I have several installed.

**Comment by LinxGem33** [comment]
@flycal6 

i don’t think it is as i tested with no extensions enable apart from arc menu but you can always test your theory, i think its a issue with either gnome shell 3.24 or version 17.04 of Ubuntu its really frustrating for developers as it seems they make changes to the code which in turn breaks some extension compatibility.

kind regards

**Comment by thefeeltrain** [comment]
I am also on 3.24 on Arch, not Ubuntu, with the exact same issue.

**Comment by yurividal** [comment]
GNOME Shell 3.24.2
same issue

**Comment by lestcape** [comment]
@LinxGem33 Just an idea. See if you have all your files in utf-8 encode.

**Comment by LinxGem33** [comment]
i believe i have found the issue i will correct now if everyone could test by manually installing.

kind regards

**Comment by yurividal** [comment]
i have tried to manually install the Arch-Menu-Master folder into ~/.local/share/gnome-shell/extentions 
but it still does not show on gnome-tweak-tool, even after reboot

**Comment by LinxGem33** [comment]
@yurividal 

make sure you change the name of the folder to arc-menu@linxgem33.com and also delete the make file in the folder and then try again and let me know after you do this please.

kind regards

**Comment by yurividal** [comment]
I works!

**Comment by LinxGem33** [comment]
fix now posted please see a33eee8

kind regards

**Comment by yurividal** [comment]
@LinxGem33 you could add these instructions ("change the name of the folder to arc-menu@linxgem33.com and also delete the make file in the folder") to the readme file... just a sugestion...

**Comment by pmorillo** [comment]
I did what it was mentioned here changing the code and still same problem
GNOME Shell 3.24.2
Ubuntu 17.04 
LG error:
![screenshot from 2017-08-25 13-00-12](https://user-images.githubusercontent.com/10132106/29724389-51078dde-8996-11e7-8146-9a44a89391eb.png)

**Comment by LinxGem33** [comment]
@pmorillo 

appreciate the feed back, could you remove the extension fully and then install **gir1.2-clutter-1.0**  << >> **gir1.2-gmenu-3.0** the terminal commands are below as you dont have the packages installed,
and reboot and try install the extension again and if you could report back and let me know if this solved your issue.
##
*example error message* 

![arc-menu error3](https://user-images.githubusercontent.com/13478564/28134003-479df2c6-6707-11e7-8a34-c0a3e704729e.png)
##
*terminal commands for required packages (search on Arch for the same packages)*

```
 sudo apt-get install gir1.2-clutter-1.0 
```
```
sudo apt-get install gir1.2-gmenu-3.0
```
##
kind regards

**Comment by pmorillo** [comment]
Thanks for getting back to me. Still no go.
I followed your steps, including reinstall manually (unzip) then make install, make enable, alt f2. Got a different error see attached.

![screenshot from 2017-08-26 01-11-00](https://user-images.githubusercontent.com/10132106/29738878-aabcbc48-89fd-11e7-9980-9893e2c3997d.png)
 Thanks.

**Comment by lexruee** [comment]
@pmorillo 
I guess you installed GNOME via the terminal. If so then the problem that you face are probably missing GNOME dependencies, which are usually installed on a GNOME-based GNU/Linux Distribution.

You can install these missing GNOME dependencies by installing the [gnome-shell-extensions](https://packages.ubuntu.com/zesty/gnome-shell-extensions) package:
```
sudo apt install gnome-shell-extensions
```
This should theoretically fix your issue.

**Comment by pmorillo** [comment]
I did uninstall then install, enable, then install shell-extensions, reboot still same error: 
ReferrenceError: Logout is not defined

**Comment by pmorillo** [comment]
Just to let you know the outcome, this PC is a laptop HP, I have other laptops where the extension works perfectly. It was on Sep 19, 201,7 a couple of days ago a new Linux update was done for the Ubuntu 17.04 OS, after that was done I tried installing again directly from the gnome extensions site, with the OFF and ON switch.  It went through like a champ, no issues, no errors, done in less than 30 seconds. So it was something on that Linux library it did not like some hardware for an HP, I suspect it is the graphics card, but not sure, no way to know now.
