### ISSUE TITLE
I still can not install in Debian Stretch

### ISSUE THREAD

**Issue by superlativo77** [LinxGem33/Arc-Menu#35]
I keep trying. I have manually installed the new master, rename file and reboot but it still does not work. 
Now appears in the Tweak Tool!!!

I'm close to getting it!

Any idea?

Thanks in advance.
![screenshot_2017-06-23_20-11-14](https://user-images.githubusercontent.com/20614565/27495476-484688b4-5852-11e7-84b8-7f0d0e4dc514.png)
![screenshot_2017-06-23_20-18-36](https://user-images.githubusercontent.com/20614565/27495478-4a6be63e-5852-11e7-96d4-039c7ea513d9.png)

**Comment by LinxGem33** [comment]
@superlativo77 

did you make sure you changed the name of the master folder to arc-menu@linxgem33.com and also delete the make file in the folder and then try again and let me know after you do this please.

kind regards

**Comment by superlativo77** [comment]
Thank you very much for the clarification. Also those steps are what I did. As you can see in the screenshot, You can see the folder arc-menu@linxgem33.com. Also I deleted makefile and reboot the machine.

I do not understand how I could install Gentoo following its Handbook and I can not install an extension in Gnome : (

**Comment by LinxGem33** [comment]
@superlativo77 
##
I’m going to close this issue as this issue seems specific to your system as other users has pointed out that the extension does work on Debian stretch.
##
![](https://user-images.githubusercontent.com/649340/27292053-6ea6c958-5512-11e7-8653-4d5cefccb56e.png)
##
kind regards
