### ISSUE TITLE
Bug: Deactivating Arc-Menu does not restore correctly the Activities button

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#38]
This issue is just for documenting a mentioned bug in: https://github.com/LinxGem33/Arc-Menu/issues/32

If Arc Menu is deactivated, then the Activities button is not restored correctly at the original default position.

Before Arc-Menu installation:
![before_installation](https://user-images.githubusercontent.com/649340/27561642-3557f638-5ac9-11e7-9d58-096c6fe85d88.png)

Installed:
![installed](https://user-images.githubusercontent.com/649340/27561648-3943e7c0-5ac9-11e7-94ab-26932688ff4f.png)

Deactivated:
![decativated](https://user-images.githubusercontent.com/649340/27561653-3e17a6ba-5ac9-11e7-9a4c-028f6069e63c.png)

**Comment by LinxGem33** [comment]
@lexruee 

i think this is a issue with gnome-shell its self when lock the screen or log out it disappears but i will try confirm this
