### ISSUE TITLE
Bug: Shell.ActionMode is undefined on Debian Jessie/gnome-shell 3.14

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#39]
This issue is just for documenting a mentioned bug in: https://github.com/LinxGem33/Arc-Menu/issues/32

Arc Menu does not work on Debian Jessie with gnome-shell 3.14. Looking glass shows the error: Shell.ActionMode is undefined.

![debian-jessie-bug](https://user-images.githubusercontent.com/649340/27562281-261c152a-5acc-11e7-97fd-0b8998a04c53.png)

I'll try to fix this bug because we claim in the metadata.json file that Arc Menu supports gnome-shell 3.14.

**Comment by LinxGem33** [comment]
on the next release ill remove support for 3.14 and also 3.16 from the metadate.jason file.

**Comment by lexruee** [comment]
@LinxGem33 
Okay, this means less work for us :smile:. Do you know if users are able to install an extension via extensions.gnome.org that is not supported by their system (i.e., gnome-shell)?

**Comment by LinxGem33** [comment]
@lexruee 
##
if i understand things correctly the user has to have three things installed on their system before any extension can be installed (1) tweak tool (2) install chrome-gnome-shelll package (3) install corresponding browser add-on , so in short if a user doesn’t have these things or the gnome desktop then its unsupported and there unable to install from extensions.gnome.org.
##
I ve also created some code to move the position of the menu its in developer discussion.
## 
kind regards
