### ISSUE TITLE
Bug: Menu search launches applications when hitting the space bar

### ISSUE THREAD

**Issue by lexruee** [LinxGem33/Arc-Menu#40]
The menu search launches applications when hitting the space bar. I'm not sure if this is a bug or a desired behaviour. For example, if I enter 'libre office' the menu launches LibreCad on my system and not LibreOffice.

I guess the main idea behind the menu search is to replace the basic application search functionality from the gnome-shell overview/expose view. In the case of the gnome-shell overview, the enter key is used to launch an application.

**Comment by LinxGem33** [comment]
also i think this is a issue with the API but i will confirm as you said the default action is to press enter for the click action.

**Comment by LinxGem33** [comment]
@lexruee 
##
**Code for Arc Menu's Position on the Panel** ( Left ,Right ,Centre )

I’ve put together this code hopefully it should help you to integrate the required code to set the position of Arc menu in the panel.
##
schema - code for the position
##
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schemalist gettext-domain="gnome-shell-extensions-arc-menu">
  <enum id='org.gnome.shell.extensions.arc-menu.visible'>
    <value value="0" nick="left"/>
    <value value="1" nick="center"/>
    <value value="2" nick="right"/>
  </enum>
    </key>
    <key name="position-in-panel" enum="org.gnome.shell.extensions.arc-menu.position">
      <default>'left'</default>
      <summary>Position in Panel</summary>
    </key>
  </schema>
</schemalist>
```
##
prefs.js - code to set the position of Arc menu on the panel either ,left,right or centre 
##
```javascript
let presentLabel = '<b>' + _("Display Options") + '</b>';
        this.add(new Gtk.Label({
            label: presentLabel, use_markup: true,
            halign: Gtk.Align.START
    }));

    vbox.add(checkContainer);

    let positionContainer = new Gtk.HBox({spacing: 5});
    let positionLabel = new Gtk.Label({label: _('Arc Menu Position on the Panel')});
    let positionSelector = new Gtk.ComboBoxText();

    positionContainer.pack_start(positionLabel, 0,0,0);
    positionContainer.pack_end(positionSelector, 0,0,0);

    ['left','center','right'].forEach(function(item) {
      positionSelector.append_text(item);
    });

    positionSelector.set_active(this._settings.get_enum(SETTINGS_POSITION));

    let self = this;

    positionSelector.connect('changed', function(pos) {
      self._settings.set_enum(SETTINGS_POSITION, positionSelector.get_active());
    });
```
##
menu.js - code for the position
##
```javascript
const SETTINGS_POSITION = 'position-in-panel';

  resetPanelPos: function() {

    Main.panel.statusArea['Arc menu'] = null;
    Main.panel.addToStatusArea('Arc menu', this, 1, this._menuPosition);

  },

  setPrefs: function() {
 
   this._prevMenuPosition = this._menuPosition;

    this._menuPosition = this._settings.get_string(SETTINGS_POSITION);
  },
```
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 
I tend to think this is a UI bug. In my opinion, it would be really nice to have the same default search behaviour as in gnome-shell. I think with some refactoring of the current source code this should be feasible.

**Comment by LinxGem33** [comment]
@lexruee 

you can never be too optimistic :smile: , if you can implement that behaviour that’s brilliant.
