### ISSUE TITLE
Code for Arc Menu's Position on the Panel

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#41]
@lexruee 
##
- (1) **Code for Arc Menu's Position on the Panel** ( Left ,Right ,Centre )

I’ve put together this code hopefully it should help you to integrate the required code to set the position of Arc menu in the panel.
##
schema - code for the position
##
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schemalist gettext-domain="gnome-shell-extensions-arc-menu">
  <enum id='org.gnome.shell.extensions.arc-menu.visible'>
    <value value="0" nick="left"/>
    <value value="1" nick="center"/>
    <value value="2" nick="right"/>
  </enum>
    </key>
    <key name="position-in-panel" enum="org.gnome.shell.extensions.arc-menu.position">
      <default>'left'</default>
      <summary>Position in Panel</summary>
    </key>
  </schema>
</schemalist>
```
##
- (2) prefs.js - **code to set the position of Arc menu on the panel either** ,left,right or centre 
##
```javascript
let presentLabel = '<b>' + _("Display Options") + '</b>';
        this.add(new Gtk.Label({
            label: presentLabel, use_markup: true,
            halign: Gtk.Align.START
    }));

    vbox.add(checkContainer);

    let positionContainer = new Gtk.HBox({spacing: 5});
    let positionLabel = new Gtk.Label({label: _('Arc Menu Position on the Panel')});
    let positionSelector = new Gtk.ComboBoxText();

    positionContainer.pack_start(positionLabel, 0,0,0);
    positionContainer.pack_end(positionSelector, 0,0,0);

    ['left','center','right'].forEach(function(item) {
      positionSelector.append_text(item);
    });

    positionSelector.set_active(this._settings.get_enum(SETTINGS_POSITION));

    let self = this;

    positionSelector.connect('changed', function(pos) {
      self._settings.set_enum(SETTINGS_POSITION, positionSelector.get_active());
    });
```
##
- (3) menu.js - **code for the position** (not sure if this is needed in the menu.js or the extension.js)
##
```javascript
const SETTINGS_POSITION = 'position-in-panel';

  resetPanelPos: function() {

    Main.panel.statusArea['Arc menu'] = null;
    Main.panel.addToStatusArea('Arc menu', this, 1, this._menuPosition);

  },

  setPrefs: function() {
 
   this._prevMenuPosition = this._menuPosition;

    this._menuPosition = this._settings.get_string(SETTINGS_POSITION);
  },
```
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 

What is the idea behind this feature?
If I understand you correctly, then the user should be able put the menu on the left corner or right corner of the top/bottom panel.

**Comment by LinxGem33** [comment]
@lexruee 
yes that is correct it allows the user to place the menu either to the left or the right or even the centre this useful in a few situations.

**Comment by lexruee** [comment]
@LinxGem33 

I believe a lot of users are going to use the Arc Menu together with dash-to-panel or dash-to-dock. This is why we should take care that Arc Menu works and harmonizes well with dash-to-panel/dash-to-dock.

I will see what I can do :-).

**Comment by LinxGem33** [comment]
@lexruee 
its not a very important feature that needs implementing i just thought that it would maybe help speed things along if we wanted to implement it :smile: , I’m going to start looking into more important features and see how we could implement them.

**Comment by lexruee** [comment]
@LinxGem33 

Since the developers of [dash-to-dock](https://github.com/jderose9/dash-to-panel) and [dash-to-dock](https://github.com/micheleg/dash-to-dock) have already implemented a similar feature, I will stick to their UI/UX guideline to use radio buttons for the menu position. I think we could also adapt their naming conventions for the tab pages :smile:. 

![screenshot from 2017-06-27 20-32-24](https://user-images.githubusercontent.com/649340/27604019-5a9ed77c-5b78-11e7-9dd4-a4d7978667a6.png)

![screenshot from 2017-06-27 20-32-57](https://user-images.githubusercontent.com/649340/27604021-5bb175e8-5b78-11e7-9c5a-17c395a8ff22.png)

**Comment by lexruee** [comment]
@LinxGem33 

I've almost fully implemented this feature. Before I make the PQ, I must refactor some parts of the implementation. By the way, I also fixed the bug in: https://github.com/LinxGem33/Arc-Menu/issues/38

It works really well with Dash-To-Panel: https://github.com/jderose9/dash-to-panel/issues/31

**Without Dash-To-Panel**
![top-right-position](https://user-images.githubusercontent.com/649340/27614265-c384fc1c-5ba0-11e7-950b-0f2425570e8d.png)

**With Dash-To-Panel: Menu at the bottom left**
![perfs-js](https://user-images.githubusercontent.com/649340/27614215-842a95f4-5ba0-11e7-939d-693a7dec95dd.png)

**With Dash-To-Panel: Menu at the bottom right**
![bottom-right-position](https://user-images.githubusercontent.com/649340/27614356-56898c8a-5ba1-11e7-81aa-b928b877a1bb.png)

**Comment by LinxGem33** [comment]
@lexruee
## 
nice job, regarding users having the position in the centre this is sometimes used in short panels or dock style panels so its definitely something we should keep if we can.
##
regarding the issue #38 good job again for spotting and rectifying the issue.
##
also i agree one of the reasons i ported this to gnome was the fact it seemed to work really well with dash-to-panel.
##
**Final thoughts**

i think the next task is that we need to do is add more tabs on the (notebook) object and name them as you said before following the UI/UX style of dash-to-dock & dash-to-panel and we need an about page with ;
- 1 Arc menu's icon at the top
- 2 Arc Menu in (header text (h1) underneath the icon or alongside
- 3 Extension Version number 
- 4 a link to the github project
- 5 a scroll box with all the developers who worked on the project named (meaning definitely you :wink:) 
##
example

**Comment by lexruee** [comment]
**PQ and Testing**
I've made a PQ into the Development-Branch: https://github.com/LinxGem33/Arc-Menu/pull/43
The PQ is tested against the following systems:

|OS                       | gnome-shell  | branch               | works     |  remarks
|-------------------------|--------------|----------------------|-----------|-------
| Debian Stretch          | 3.22         | Development-Branch   | yes       |
| Debian Sid (my system)  | 3.22         | Development-Branch   | yes       |
| Ubuntu Gnome LTS 16.04  | 3.18         | Development-Branch   | yes       |
| Ubuntu Gnome 17.04      | 3.24         | Development-Branch   | yes       |
| Arch Linux              | 3.24          | Development-Branch   | yes    | Tested with wayland.

**Comment by LinxGem33** [comment]
@lexruee 
##
:laughing: i like the sentiment, ill test the latest PR against my test systems and report back and your more than welcome you have put a lot of hard work into this project and its much appreciated by me and everybody else who is using this extension.
##
kind regards

**Comment by LinxGem33** [comment]
@lexruee 
##
just a quick update, I’ve tested against all my testing machines and its another solid release, i felt comfortable enough to release this upstream to extensions.gnome.org.
##
![set1](https://user-images.githubusercontent.com/19158615/27656156-e14eb2a2-5c3f-11e7-92d7-45179de3feb5.png)
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 

This is great news. 

Here is an example regarding the about page. It is just a first draft and needs some additional refinement. I took the Arc-Menu icon from extensions.gnome.org page. Is this icon also licensed under the GPL2?
![about-page](https://user-images.githubusercontent.com/649340/27656805-b42090ba-5c4a-11e7-9b8e-9dfabb8ce99a.png)

**Comment by LinxGem33** [comment]
@lexruee 
##
yeah that’s definitely the direction to go for the about page, i was thinking if your going to add the about page maybe add these pages;
##
- 1 General 
- 2 Appearance
- 3 Behaviour 
- 4 Fine tune 
- 5 About
##
what do you think about this name scheme? and what do you think about putting the corresponding features with the corresponding categories.

**Comment by LinxGem33** [comment]
@lexruee 
##
I’ve just designed a new icon for arc menu ill release it under a v3 GPL license let me know what you think. 
##
![arc-menu-icon](https://user-images.githubusercontent.com/19158615/27659238-a1907fd2-5c4a-11e7-8e87-72c4fbda484e.png)
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 

**Icon**
Both icons look great. You must know I'm not a designer so I can't really tell which one is better. Following the KISS principle and minimalist design philosophy, I prefer the first one. But it is up to you to make this design decision :-). I'm more a backend software developer ;-).

Here is a preview how it looks on the about page:
![about-page-2](https://user-images.githubusercontent.com/649340/27660263-df146d26-5c56-11e7-82d7-0119534c9b73.png)


**Tab page organization and future features**
I agree that we should adapt a naming scheme like the one of dash-to-panel. In our case: General, Appearance, Behaviour, Fine tune and About.

>what do you think about putting the corresponding features with the corresponding categories?

That is definitely a good idea. This helps users that are already familiar with dash-to-dock/dash-to-panel to use Arc Menu. But before we add more tab pages, we should have at least some useful features for each category.

**Comment by LinxGem33** [comment]
@lexruee 
##
Regarding the icon i liked the first one as well i will update the icon upstream and you can use this icon for the about page.
##
I’ve put together a chart below for a visual help where to put the the corresponding features with the corresponding categories these have all been collated from our planned features list, this should help us place the correct features in the correct categories when creating the prefs.js settings, let me know what you think.
##
|Category|Feature|Comment|
|:-----:|:-----:|:-----:|
|General| (1) Disable/enable individual categories from the settings menu (prefs.js) (2) Disable/enable suspend button (3) Gui option to enable/disable a Terminal shortcut (4) Gui option to enable/disable a System Monitor shortcut
|Appearance|(1) GUI option for changing the panel icon (2)  Gui Option to set the menu on left or right  (3) Resizeable menu
|Behaviour|  (1) Gui option to enable/disable the default top left hot corner (2) Gui option to bind the Super Key to the Arc Menu (3) Gui option to bind a custom keybinding to the Arc Menu 
|Fine Tune| (1) Add hints/tool tips to the menu buttons (power, lock, logout, suspend) (2) Gui option to enable/disable tool tips
|About||just a info page|
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 

That is a nice table and overview of some future features. I would suggest you add this table in the github issue: https://github.com/LinxGem33/Arc-Menu/issues/42

Concerning the about page, I made a PR here: https://github.com/LinxGem33/Arc-Menu/pull/44

To complete the about page, you need to add a logo.png file in the media directory.

**Comment by LinxGem33** [comment]
@lexruee 
I’ve merged the latest changes and ill test them on my test machines and report back.
