### ISSUE TITLE
New Official Arc Menu Logo Icon

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#45]
@lexruee 
##
its taken me a little while but i have finally designed the new official Arc menu logo icon as i wasnt happy with the other icons ill release this under a v3 GPL license, please see below the finished product and also with the icon applied to the about page, let me know what you think.
##

![ark-game3 svg](https://user-images.githubusercontent.com/19158615/27668420-e708de28-5c78-11e7-8224-954b3f8e994c.png)
##
![ab3](https://user-images.githubusercontent.com/19158615/27668914-c18a0bc4-5c7b-11e7-82d7-2c5225b33ee1.png)

**Comment by lexruee** [comment]
@LinxGem33 
:+1: Looks great! I would suggest you add the logo file to the Development-Branch and adapt the about page :-).

This is also a nice logo for our future Arc-Menu Project Website ;-): https://pages.github.com/

![screenshot from 2017-06-29 04-36-06](https://user-images.githubusercontent.com/649340/27668985-9409de00-5c84-11e7-96dc-62b12436818b.png)

**Comment by LinxGem33** [comment]
@lexruee 
:smile: , I’ve just created a organisation and sent you a invitation and this will allow us to both have access and we can create a  github web page from there also i have updated the development branch with the new icon logo and placed it in the media folder and renamed it to the correct naming convention.
##
regarding creating a menu button i will create that  to the correct size so we can use it.
##
regarding the license v3 GPL it just gives anybody creative freedom.

**Comment by LinxGem33** [comment]
@lexruee 
##
I’ve finished the panel button icons, these are just PNG's but i have the SVG's ready for use with the shell, when designing the icons they had to be one colour as you would have readability issues if they had colour in them (you wouldn’t be able to see them properly) let me know what you think.
##
|Dark Panel Icon|Light Panel Icon|
|-----|-----|
|![pda](https://user-images.githubusercontent.com/19158615/27677344-36ecf73c-5ca9-11e7-90f2-851016dd390b.png)| ![pla](https://user-images.githubusercontent.com/19158615/27677362-4c2b612e-5ca9-11e7-97ae-a64d5b5cf7e1.png)|

**Comment by lexruee** [comment]
@LinxGem33 
Great job! The next feature on my to-do list is "GUI option for changing the panel icon" :-).

**Comment by LinxGem33** [comment]
@lexruee 
that’s great news ill open a new issue so we discuss there about this feature,in the meantime ill continue setting up the Arc menu organisation, and look for some code that maybe will speed up development.
