### ISSUE TITLE
GUI option for changing the panel icon/text

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#46]
@lexruee 
all discussion regarding this feature can be made here :smile:

**Comment by lexruee** [comment]
@LinxGem33 
Thanks to the great gnome-shell javascript documentation, I was able to quickly prototype a GUI for the appearance tab :smile:. And yes it is working! 

Here are some screen shots. The idea is that the user can easily select between different button appearances, namely "Icon", "Text", and "Icon and Text". For further customizations of the menu button the user can click on the extra settings button. 

**Menu button with the icon appearance**
![icon-text-1](https://user-images.githubusercontent.com/649340/27704248-33df8f9e-5d0a-11e7-9d9b-53a89be636df.png)

**Menu button with the text appearance**
![icon-text-2](https://user-images.githubusercontent.com/649340/27704253-3768d8c8-5d0a-11e7-9209-344181fc8d29.png)

**Menu button with the icon and text appearance**
![icon-text-3](https://user-images.githubusercontent.com/649340/27704260-40944b62-5d0a-11e7-8cef-b6a449ade11b.png)

The next step involves prototyping the extra settings window where the user can pick a custom icon or define a custom text for the menu button.

**Comment by LinxGem33** [comment]
@lexruee 
##
fantastic work, i really like the concept this is probably one of the most wanted feature's for a applications menu in Gnome 3 that is currently missing.
##
i have now set up the security and repositories for the arc menu application in the [Arc menu organisation](https://github.com/Arc-Menu) -  :smile:  I’ve uploaded all the latest development branch files and dependences to the Gnome-Arc-Menu repository i have set your permissions for read and write access which will save you time when you want to push a feature or code correction upstream for prototyping.
##
my next task is to start the foundation for our website for Arc menu and to find a style for our website and create all art work for that.

**Comment by lexruee** [comment]
Finally, I got the Gtk.Dialog thing working. Again, the javascript documentation is really great (irony). In short, I read the Python documentation and then I try to translate it to javascript :smile:.

**Arc-Menu-Prototype: Set custom text for the menu button**
Here is a funny demo that shows what happens if you change the text for the menu button.

[![Arc-Menu-Prototype: Set custom text for the menu button](https://i.ytimg.com/vi/9m9FkCYkQ3Y/hqdefault.jpg)](https://youtu.be/9m9FkCYkQ3Y "Arc-Menu-Prototype: Set custom text for the menu button")

**Comment by LinxGem33** [comment]
@lexruee 
really good work, its good how you have managed to get the options widget to work by translating the python documentation and adapting it to JavaScript, really like the youtube video it helps to see and visualise the progress good idea, i was thinking maybe have a bit more spacing between each feature, what do you think?
##
also I’ve added some new feature ideas for you to look at on the ideas page #42  maybe it might inspire you :smile: its just some things that came to mind that i thought would be a good idea to log just in case, i also adjusted the feature table accordingly.
##
**website update**
I’ve also been looking this evening at possible templates for our website ill organise a selection for you to take a look at in the coming days hopefully, just to get your feed back on which one we should take forward for the official website.

**Comment by lexruee** [comment]
@LinxGem33 

I'm familiar with writing code in Python/JavaScript. But it is frustrating if you need to use 4 different sources of documentation to write a JavaScript based application for gnome-shell. Anyways, the best documentation is always the source code itself: https://github.com/GNOME/gnome-shell

**Spacing between each feature**
I assume you would like to have a vertical spacing between each feature like in dash-to-panel. Is this correct? Moreover, dash-to-panel uses panels to group related features.

See my fantastic drawing skills for marking the vertical spacing in the figure below:
![dash-to-panel-spacing-marked](https://user-images.githubusercontent.com/649340/27714965-7783a2c4-5d34-11e7-8125-4efba650a703.png)

**RE: ideas update**
I will have a look at it.

**RE: website update**
I'm looking forward to it.

**Comment by LinxGem33** [comment]
@lexruee 
##
**spacing**

yes that is correct apologies i should have been more clear i mean vertical spacing between each feature :smile: i was just wondering if it was possible and it wouldn’t impact on your work flow, also thank you for that link i will take a look at that.
##
**thoughts**

in the last four months i have learned more about gtk and gnome shell development then in the last 2yrs considering i had no previous coding knowledge and that’s just by throwing myself in the deep end "so to speak" and i must say i am learning a great deal working and collaborating with you so thank you.

**Comment by lexruee** [comment]
@LinxGem33 
I made a mockup for the "button appearance" dialog window. In case you're interested in creating GUI mockups, I used the awesome [evolus pencil program](http://pencil.evolus.vn/). It should be available in most Linux Distributions.

I must say designing a self-explanatory GUI is not an easy task :smile:. Here is the mockup:
![button-appearance-window](https://user-images.githubusercontent.com/649340/27765923-eec1255a-5ebf-11e7-8501-03abcc97317d.png)

The idea behind the GUI is as follows:
* The first panel groups the text options
  * System text <=> Use default system text (i.e., Applications for English, Applikationen for German, etc)
  * Custom text <=> User-defined text for the menu button
* The second panel groups the icon options
  * The GUI combo box allows the user to choose from a set of predefined icons: Arc Menu Icon, System Icon (Gnome Icon), Custom Icon
  * For selecting a custom icon, the user has to choose Custom Icon in the combo box and the user has to click on the image icon, which opens a file dialog.

Let me know what you think about this mockup. I'm thinking about how the custom icon option could be simplified. With the mockup above, the user needs to click on two GUI elements to accomplish this task.

**Comment by LinxGem33** [comment]
@lexruee 
##
**custom icon**
 
i really understand the concept its really clear and concise, one possible solution to make the custom icon easier to simplify would be to have the user import a icon on the icon option and use that icon no matter which other option the user clicks on (until the user changes the icon again in the icon option) i.e all the other options import that icon and do the same for the text option and with the icon & text option that would import the predefined icon or text that the user has set previously this would reduce the need for more clicked element pop-ups as both the icon and text options would have been pre-set
let me know what you think about this solution.
##
**website update**

(https://arc-menu.github.io/Arc-Menu-Group/)

as you have probably noticed i have been quite this evening as its taken me all night to configure the website for github pages as the template we chose had many bad coding issues which needed to be resolved but i finally managed to configure and i have now started to design and start adding information, you can see the progress by clicking the link above, it also has a blog section which i will configure after i finish designing let me know what you think so far also check out the about page I’ve listed you there :smile:

**Comment by lexruee** [comment]
**RE: Mockup, GTK implementation, and custom icon**
Et voilà. Here is the latest mockup (the file I sent to you ) and the GTK implementation of it.

***Mockup***
![button-appearance-window-2](https://user-images.githubusercontent.com/649340/27767040-9025b164-5ee7-11e7-9b17-c42309a4e692.png)

***GTK Implementation***
![screenshot from 2017-07-02 05-28-42](https://user-images.githubusercontent.com/649340/27767035-5f16deae-5ee7-11e7-8eef-fb5b339daae7.png)

Remarks:
 * With this GUI design, the user can click on the folder icon to select a custom icon or the user can select a predefined icon via the combo box.
* If the user selects a custom icon via the folder icon, then the combo box is set to "Custom Icon".


Overall, I think this GUI is cleaner. However, I'm not an UI/UX expert :smile:.

**Re: website update**
No hurry. We have enough time to setup a website :smile:. Good things need time.
Short question are you a member of the OSX-Arc-Group on github? They forked all your themes.
See: https://github.com/OSX-Arc-Group

**Comment by LinxGem33** [comment]
@lexruee 
##
regarding the implementation of the the system icon that’s exactly what i was meaning when i said;
> one possible solution to make the custom icon easier to simplify would be to have the user import a icon on the icon option and use that icon no matter which other option the user clicks on (until the user changes the icon again in the icon option) i.e all the other options import that icon and do the same for the text option

i agree its much cleaner and more concise in its implementation  which limits the need for more user clicks, overall I’m really impressed with the progress your making with this feature its something that is lacking in many gnome 3 application menu's and i can definitely see this being forked into other Gnome/GTK desktop environments, regarding the UI/UX aspect Ive worked with a few UI developers and i don’t think it would been set out any different :wink: 
##
![](https://user-images.githubusercontent.com/649340/27767035-5f16deae-5ee7-11e7-8eef-fb5b339daae7.png)
##
regarding the OSX-Arc-Group its another gtk3 developer who himself has designed a lot of themes and is well known that reached out to me as i stated that i would be stopping developing my themes as i had time constraints and he said he would maintain them with me until i have more time as i want to concentrate on my extension development :smile:

**Comment by lexruee** [comment]
@LinxGem33 
I stumbled across the following option in the Tweak Tool when I looked for an existing solution in Gnome (Shell theme option):
![screenshot from 2017-07-02 06-31-53](https://user-images.githubusercontent.com/649340/27767226-2fb57e96-5ef0-11e7-8eb5-931eefd6e6ea.png)

And later I scanned your comment, then I thought let's implement it this way :smile:. Regarding this feature, the next step involves implementing the application logic and refactoring some code. 

**Arc-Menu Organization**
Short question: Are you planning to transfer this repository to the [Arc-Menu](https://github.com/Arc-Menu/) organization? You can later fork it again to your github account. In my opinion, it would be nice to keep the git history in this repository.

**Comment by LinxGem33** [comment]
@lexruee 
##
sounds good cant wait to see the finished result were definitely on the right track like you said just need to get up and running :smile: 
##
regarding Arc-Menu-Organisation i manually upload any changes to the repository so this repository will hopefully always be left in tact so the git history will be the same :+1:

**Comment by lexruee** [comment]
@LinxGem33 
A short update. 

Here is a screenshot of the current and fully working GUI prototype:
![screenshot from 2017-07-04 01-56-36](https://user-images.githubusercontent.com/649340/27810553-17664362-605c-11e7-80fd-b9938cfca949.png)

I decided to add a UI slider (ie., [Gtk.HScale](https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.HScale.html)) to the GUI for adjusting the icon size. In my opinion, this a handy feature :smile:. And because making youtube videos is fun and a nice distraction from doing other things, I made video that shows the current progress of this feature.
[![Arc-Menu-Prototype: Set custom text for the menu button](https://i.ytimg.com/vi/Eji8DeqSy5Y/hqdefault.jpg)](https://www.youtube.com/watch?v=Eji8DeqSy5Y "Arc-Menu-Prototype: Menu button customization")

Overall, I'm almost done with it. I will make soon the pull-request.

**Comment by LinxGem33** [comment]
@lexruee 
##
its looking really good now :+1: you’ve done a excellent job we just have a few more minor features left to implement and then its definitely out of the beta phase so to speak i have now finished testing  both website templates and when we finish the remaining features we can set that up straight away, also i can now help out with feature development  now that I’ve finished with the website templates, i will start organising some code for some of the features to help you speed things up with code development just let me know which feature you want to work on after this and ill get started and send you the code to review or if you need artwork etc :smile: 
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 
Finally, I made the pull-request for this feature: https://github.com/LinxGem33/Arc-Menu/pull/48
I'm currently testing this pull-request on my test systems.

**Comment by LinxGem33** [comment]
@lexruee 
##
just a quick update I’ve tested new PR against my testing machines (gnome-shell 3.18 - 3.24) and everything is working good, i also added the SVG icon to the media folder for the default icon and compiled for upload to upstream to extensions.gnome.org.
##
**Dash to dock** (passed)

![apm3](https://user-images.githubusercontent.com/19158615/27911105-c878f470-624f-11e7-8189-ed29ba1278ff.png)
##
**Dash to panel** (passed)

![apm5](https://user-images.githubusercontent.com/19158615/27911117-d14c1fc8-624f-11e7-81e4-b8eaa5953262.png)
##
settings prefs.js (passed)

![apm](https://user-images.githubusercontent.com/19158615/27911129-da7c71b0-624f-11e7-849f-9c4a0e8da31c.png)
##
**Icon settings** (passed)

![apm1](https://user-images.githubusercontent.com/19158615/27911139-e27ba84a-624f-11e7-87d0-1e22d086acf8.png)

**Comment by LinxGem33** [comment]
@lexruee 
tested and everything is working really good job :smile:
