### ISSUE TITLE
Website considerations 

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#47]
@lexruee 
##
its taken me a little while but Ive finally got a collection of potential website templates for consideration let me know which one you like and ill get started in designing :smile: please see below the links for demo’s of the websites. 
##
- (1) [incorporated](http://incorporated.sendtoinc.com/)

- (2) [mmistakes](https://mmistakes.github.io/minimal-mistakes/)

- (3) [solid](http://ojs.xyz/solid-jekyll/) (i like this one)

- (4) [skinny-bones](https://mmistakes.github.io/skinny-bones-jekyll/)

- (5) [type-theme](https://rohanchandra.github.io/type-theme/)

- (6) [daktilo](http://daktilo.github.io/)

- (7) [deanattali](http://deanattali.com/beautiful-jekyll/)

##
**thoughts**

thanks for the email yesterday did you get my reply?

**Comment by lexruee** [comment]
@LinxGem33 
I was a little bit busy today :smile:. The theme (3) solid looks good :+1: .

**Re: thoughts**
Yes, I did receive your email.
