### ISSUE TITLE
Translations are not working.

### ISSUE THREAD

**Issue by pkomur** [LinxGem33/Arc-Menu#5]
Translation into Polish language not works.
I didn't check other languages.

**Comment by LinxGem33** [comment]
@pkomur 

appreciate the feed back, could i have a little more information about your system OS, version, desktop etc so i can look into the issue.

kind regards

**Comment by pkomur** [comment]
Kernel: 4.10.0-21-generic x86_64 (64 bit), Desktop: Gnome 3.24.1, Distro: Ubuntu 17.04

**Comment by TheElixZammuto** [comment]
Arch Linux with kernel 4.10.13-1-ARCH, same problem with Italian Language, "Activities Overview", "Type to Search" and many other are still in english

**Comment by LinxGem33** [comment]
@TheElixZammuto 

appreciate the feed back, I’m going to mark this as a bug as multiple users are having the same problem, ill look into this issue and see if i can resolve it as soon as possible.

kind regards

**Comment by LinxGem33** [comment]
v3 has now been released with more fixes and is available to update on extensions.gnome.org could you test and let me know if the issue still persists.

kind regards

**Comment by pkomur** [comment]
There was bug in metadata.json file.
I also added compiled version of Polish translation file.

**Comment by h3r0n** [comment]
Fedora 25 here. I still see the menu in English, although my locale is it_IT.

**Comment by LinxGem33** [comment]
sorry guys for the late reply i haven’t forgotten about this issue i will hopefully make this my next bug to fix.

kind regards

**Comment by Elbullazul** [comment]
@letscape @NikoKrause would you guys want to help?

**Comment by lestcape** [comment]
@Elbullazul I have not any idea of how the translation works in gnome shell... I create my own translation mechanism. I don't know what will be the idea with this...

**Comment by LinxGem33** [comment]
hi everyone 

The foundations have now been set-up and are ready for the translations for Arc menu but we need people to translate into there respective languages as you can understand i am unable to translate in other than English as this is my native language all the information you need to do this is on the main page  in the advanced installation section please help us so we can help you.

kind regards - *LinxGem33*

**Comment by TheElixZammuto** [comment]
Working on the Italian Translation, I'll make a PR when done

**Comment by lexruee** [comment]
@TheElixZammuto 
We have already a Italian Translation here:
https://github.com/LinxGem33/Arc-Menu/pull/57

 But maybe you can help us on the review on this pull-request.
