### ISSUE TITLE
A/Z button to change from category view to A/Z view

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#50]
@lexruee 
##
i think this is the last major feature to implement, let me know what you think of my concepts below regarding feature implementation.
##
- (1) A/Z button to change from category view to A/Z view

|example|
|:-----:|
|![azm](https://user-images.githubusercontent.com/19158615/27812788-53e55b68-6069-11e7-96b7-29f4fc8e6f57.png)|
|*options on the drop down box would say* 
ALL= AZ view > 
CATEGORIES = categories view > 
RECENT = recent apps view >|

**Comment by LinxGem33** [comment]
@lexruee 
also updated your contributions list on main page :smile:

**Comment by lexruee** [comment]
Hey, thanks. But I guess we will need to introduce a changelog for that :smile:. I'm not sure but such a changelog could be automatically generated from the git logs.

Regarding the A/Z view, I think I understand the idea. The challenging part is to get the UI of the AZ view right. When I hear AZ-view, I always think of the Windows 10 menu:

![az-view](https://user-images.githubusercontent.com/649340/27917777-4fb80ae4-626d-11e7-97ea-59afe02ece86.png)

In short, I have the following understanding about this feature:
 * The categories view is already the default view of the Arc Menu. So this view is already implemented.
 * The AZ-View is a view (i.e., list) where all applications are listed in a alphabetical order (figure above).
 * The recent apps view is a view (i.e., list) of the recently used applications.

One question that I have is if only one view can be used at a time or if different views can be mixed?
For example, a menu only with a recent apps view might be less useful. But combined with a AZ-View it  can be useful.

**Comment by LinxGem33** [comment]
@lexruee 
##
we could maybe implement this feature by adding the code like this, let me know what you think.
##
**schema**

```xml
  <enum id='org.gnome.shell.extensions.arc-menu.appsDisplay'>
    <value value='0' nick='All'/>
    <value value='1' nick='Categories'/>
    <value value='2' nick='Recent'/>
    <value value='3' nick='None'/>
  </enum>
```

##
**prefs.js**

```javascript
        let startupAppsDisplayLabel = new Gtk.Label({label: _("Applications to display at startup"),
                                                        hexpand:true, xalign:0});
        let startupAppsDisplayCombo = new Gtk.ComboBoxText({halign:Gtk.Align.END});
            startupAppsDisplayCombo.set_size_request(120, -1);
            startupAppsDisplayCombo.append_text(_('All'));
            startupAppsDisplayCombo.append_text(_('Categories'));
            startupAppsDisplayCombo.append_text(_('Recent'));
            startupAppsDisplayCombo.append_text(_('None'));
            startupAppsDisplayCombo.set_active(this.settings.get_enum('startup-apps-display'));
            startupAppsDisplayCombo.connect('changed', Lang.bind (this, function(widget) {
                    this.settings.set_enum('startup-apps-display', widget.get_active());
            }));

        startupAppsDisplayBox.add(startupAppsDisplayLabel);
        startupAppsDisplayBox.add(startupAppsDisplayCombo);



        let columnCount = [3, 4, 5 , 6, 7];
        let appsGridColumnCountBox = new Gtk.Box({
            spacing: 20,
            orientation: Gtk.Orientation.HORIZONTAL,
            homogeneous: false,
            margin_left: 20,
            margin_top: 5,
            margin_bottom: 5,
            margin_right: 10
        });
```

##

**Comment by LinxGem33** [comment]
@lexruee 

please see a small start to the UI for the settings, the logic still has to be implemented its just a rough start to the AZ feature and also the recent apps etc.
##

![go5](https://user-images.githubusercontent.com/19158615/28996852-7cece0e4-79ff-11e7-9115-1b79aad08312.gif)

**Comment by LinxGem33** [comment]
closed due to new development called MULTI - MENU which is a selectable multi configurable option hopefully to be released.

see #42
