### ISSUE TITLE
Activities Overview can only be closed with "ESC"

### ISSUE THREAD

**Issue by danielstuart14** [LinxGem33/Arc-Menu#60]
When you open the activities overview through the shortcut, you will only be able to close it using esc or going through the menu and clicking in the shortcut again. (If you are using the Super key for the menu + with the hot corner disabled. Which I think is how everybody's shell is setup when using Arc)

Also, you can open the Arc Menu while the activities overview is opened, which is kind of odd.

Maybe, we could set it to close the activities overview (if it's opened) when we open the Arc Menu. (So, it'll close the activities overview and then open the menu)

(Btw, Arc is the best linux menu man!)

**Comment by lexruee** [comment]
@danielstuart14 
Regarding opening the menu while the activities overview is opened: this is a feature not a bug :smiley:.

Anyways, I will have a look at the issues that you mentioned. Currently, the localization feature has a higher priority to me :smiley:.

**Comment by LinxGem33** [comment]
@danielstuart14 

i don’t think this is a inherit issue with Arc menu extension rather the behaviour from gnome shell please see this issue [#192](https://github.com/jderose9/dash-to-panel/issues/192) posted on dash-to-panel which i think relates to your issue.

kind regards
