### ISSUE TITLE
Latest version  can't be installed from https://extensions.gnome.org/

### ISSUE THREAD

**Issue by ceyhunnabiyev** [LinxGem33/Arc-Menu#66]
![screenshot-20170710094227-1333x387](https://user-images.githubusercontent.com/5506156/28004211-2b46e7d6-6554-11e7-968c-ea0631da57c8.png)

Regards..

**Comment by ceyhunnabiyev** [comment]
Latest version doesn't work only,  previous versions can be installed.

**Comment by LinxGem33** [comment]
@ceyhunnabiyev 
##
appreciate the feed back, i have tested on all my testing machines and its working i am able to download the latest version from extensions.gnome.org, if you haven’t already make sure you have all the required extension for Firefox and gnome so you can use extensions.gnome.org also make sure you uninstall any previous version of the extension just to make sure and try install again, if you still cant install try a manual install by; 
##
downloading from here >> then extract zip file >> then right click and choose open in terminal >> then type in terminal `make compile` >> then type `make install` >> then log out and back in >> then switch on extension from tweak tool. 

let me know what happens and also give me some details about your set-up OS.. desktop etc if this doesn’t resolve your issue.
##
**latest version installed**
![awo](https://user-images.githubusercontent.com/19158615/28004834-06074660-653f-11e7-8a3b-d8fd145bdc14.png)

**Comment by lexruee** [comment]
@ceyhunnabiyev 
Without any additional information about your system, we can only speculate what the problem is. So, please provide us information about your GNU/Linux distribution and the GNOME Shell version. Otherwise, your problem is just a Higgs-Bugson for us.

> A hypothetical bug predicted to exist based on a small number of possibly related event log entries and vague anecdotal reports from users, but it is difficult (if not impossible) to reproduce on a dev machine because you don't really know if it's there, and if it is there what is causing it. (see Higgs-Boson)

source: https://blog.codinghorror.com/new-programming-jargon/


Command to retrieve information about your distribution:
```
lsb_release -a
```
Command to retrieve information about your GNOME Shell version:
```
gnome-shell --version
```

**Comment by ceyhunnabiyev** [comment]
> gnome so you can use extensions.gnome.org also make sure you uninstall any previous version of the extension just to make sure and try install again

This answer solved my problem. I had installed with clicking update icon  that you showed in the picture. 
Thanks for your answers..
