### ISSUE TITLE
Super key does not open menu

### ISSUE THREAD

**Issue by fr3dm4n** [LinxGem33/Arc-Menu#7]
To replace the Gnome overlay completely, one should have at least the option to open the arc menu via pressing [super]. Otherwise one is forced to use the mouse/touchpad

**Comment by LinxGem33** [comment]
@fr3dm4n 

appreciate the feed back, my first initial priority was to get this extension stable enough to upload to extensions.gnome.org as this was a menu baked into the Zorin OS operating system so it had to be ported to work with the gnome shell eco system, once i iron out the bugs which appear after this first release i can then move onto stage two which is to start adding new features among them is to add the ability to bind the super key to the menu.

kind regards

**Comment by fr3dm4n** [comment]
Ah! Zorin! It looked so familiar! :smile: 
No need to hurry. The menu is great and this ticket should just be a reminder. I'm pretty sure you would have done it anyway.

BTW: Great work so far!

**Comment by marksev1** [comment]
Basically it would be great if there was the possibility to bind a key of my preference to open the menu, because not all of us use the super key for opening up the menu.

**Comment by lestcape** [comment]
@marksev1 what you request apparently is against of what gnome developers want to have https://bugzilla.gnome.org/show_bug.cgi?id=778809 ... They have a lot of restriction making difficult create a general procedure to do something like this. Anyway i implemented a buggy (for now) general procedure for my global menu https://github.com/lestcape/Gnome-Global-AppMenu

**Comment by lestcape** [comment]
If i have the time to fixed the procedure that i have i will create a pull request for add the ability here.

**Comment by LinxGem33** [comment]
@lestcape 

i would really appreciate that and thank you so much for taking the time, at the moment I’m working on the prefs.js for the arc menu.

kind regards

**Comment by alexeymuranov** [comment]
Just an ability to set up a keyboard shortcut to open the menu would be good enough for me. Otherwise i am stuck with having [some kind of quick launcher](https://extensions.gnome.org/extension/973/switcher/) installed besides.

**Comment by lestcape** [comment]
@alexeymuranov is not easy, because by default when there are a modal actor (all menus in gnome shell are modals), gnome shell disable the key-binding mechanism. So, you can easy open a menu with a hokey, but to close it with a hotkey, will be the problem, because as the menu are opened the key-binding mechanism are disable. You can easy used the key-binding mechanism with not modal actors, like the example that you mention.

**Comment by marksev1** [comment]
Gnomenu has the ability to use other keys for opening it versus the super-key.

**Comment by lexruee** [comment]
@LinxGem33 
I played around a little bit with the overlay key. So far I figured out how we can deactivate the overlay key and reactivate the default behaviour of the overlay key. As you stated on another github issue this can be achieved using the `Gio.Settings` API. A demo can be found on my [super-key](https://github.com/lexruee/Arc-Menu/tree/super-key) branch.

Example extension.js:
```javascript
let mutterSettings;
...

// Enable the extension
function enable() {
    ...
    mutterSettings = new Gio.Settings({ 'schema': 'org.gnome.mutter' });
    unbindOverlayKey();
}

// Disable the extension
function disable() {
    ...
    bindOverlayKey();
    ...
}

function unbindOverlayKey() {
    // simple hack to deactivate the overlay key by setting 
    // the keybinding of the overlay key to an empty string
    mutterSettings.set_string('overlay-key', '');
}

function bindOverlayKey() {
    // restore the default settings
    let defaultOverlayKey = mutterSettings.get_default_value('overlay-key');
    mutterSettings.set_value('overlay-key', defaultOverlayKey);
}
```

**Comment by lestcape** [comment]
@LinxGem33 you have right. This is also how this work on cinnamon. They also have a global function to remove the custom key-binding: https://github.com/linuxmint/Cinnamon/blob/master/js/ui/keybindings.js#L65 this function (or an equivalent) is not present in gnome shell. I also don't implemented this typ of thing yet for the global menu.

**Comment by LinxGem33** [comment]
@lexruee 

yeah that’s totally the way to do it but there then has to be a option on the prefs/settings.js  so the user can activate the binding as @lestcape  stated before as gnome binds the shell overview to the super key it has to be used in conjunction with another key binder i.e (super+ L) for example the gio-settings allow you to modify the function of the overlay key binding, in short you are on the right track but it will need a prefs.js file and a schema setting to unify the two settings, but really well done you’ve done a really good job ill test your branch and see what i can find.

kind regards

**Comment by lexruee** [comment]
@LinxGem33 
I totally agree with you that we need a settings menu (prefs/settings.js). However, for prototyping, I like to make small changes to a code base and to test if a solution approach really works :-). So consider my comment only as demo how to fix the "overlay key issue" :-).
In the following days I'll try to figure out more stuff how the super key can be bound to the menu.

**Comment by LinxGem33** [comment]
@lexruee 

really well done you have got further than me on this issue as you know Im still learning but your definitely going in the right direction on this issue.

kind regards

**Comment by lestcape** [comment]
@LinxGem33 and @lexruee see this file and specially this function: https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/settings/keybindingWidgets.js#L241

This is a custom implementation to handled key-bindings. As is custom, i can capture any combinations and not what gnome (gtk) defined as a save combination. Then i can used as a key binding <super> in a combination with the @lexruee solution. This implementation have only one problem. The keyboard Gtk events non report the group (this is an integer that representing the selected language of the keyboard) and is needed to translate the keyboard state group (https://people.gnome.org/~gcampagna/docs/Gdk-3.0/Gdk.Keymap.translate_keyboard_state.html) base on the active layout (the effective_group) In python + Gtk the keyboard effective group come with the keyboard event in gjs not and i don' t know how get it, so it's set to the primary one (https://github.com/lestcape/Gnome-Global-AppMenu/blob/master/gnomeGlobalAppMenu%40lestcape/settings/keybindingWidgets.js#L252) and that is an error.

**Comment by lestcape** [comment]
For reference the key-release-event https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.Widget-key-release-event.html provide a Gdk.EventKey, https://people.gnome.org/~gcampagna/docs/Gdk-3.0/Gdk.EventKey.html with come with the group property, but in practice is not set.

**Comment by lestcape** [comment]
I fix the code of on_key_release:
```
    on_key_release: function(widget, event) {
        this.ungrab();
        this.teaching = false;
        event = this.press_event;

        let display = widget.get_display();
        let [, keyval] = event.get_keyval();
        let group = event.group;
        let [, accel_mods] = event.get_state();
        if(group === undefined) {
            group = 0;
            let [ok, keys] = Gdk.Keymap.get_default().get_entries_for_keyval(keyval);
            if(ok && keys.length > 0) {
                group = keys[0].group;
            }
        }
.....
```
So, i think this is now usable.

**Comment by LinxGem33** [comment]
@lestcape 
its looking good @lexruee  is working on this s o i think this will help alot thank you

**Comment by lestcape** [comment]
Ok, as i say when i fixed this problems, i will port it to Arc-Menu the solution... But of course i don't know if i can finish it. So, if i have a progress I will share it. If @lexruee resolved it first better.

My problem is find a general way that can work on all scenarios, because the intention of what i'm doing is load the cinnamon applets inside gnome shell, so i can not make conceptions, because i don't know which is the default keybinding of the cinnamon applets. Maybe you do not need to find something so general for Arc-Menu.

**Comment by lexruee** [comment]
@marksev1, @fr3dm4n, @alexeymuranov
For all users that are interested in this feature, I made a Youtube-Video that shows the current Arc-Menu-Prototype.

**Arc-Menu-Prototype: Super key binding and Menu positioning**
[![Demo](https://i.ytimg.com/vi/X_Wiwlviu5w/hqdefault.jpg)](https://www.youtube.com/watch?v=X_Wiwlviu5w "Video Title")

**Comment by nutritiousreject** [comment]
The Super key opening the menu works great!
While testing it out though i noticed that if I newly installed a program, it wouldn't show up in the Arc Menu

This does not happen on the master branch

https://gfycat.com/ClumsyWhoppingFlounder

**Comment by kushalchauhan98** [comment]
The Super Key does work, but the other <Super>+<Key> shortcuts (such as window tiling) no longer work. Could it be done so that the menu shows up only on <Super> press, but not on <Super>+<Key> combinations?
Great work by the way!

**Comment by yurividal** [comment]
yeah. works but disables all other shortcuts. i have super+D for desktop, for example...

**Comment by lexruee** [comment]
@yurividal 
Does this problem occur when you use the left Super Key?
If this is the case, then this not really a bug since the the GNOME developers did not intend the misuse of the left super key for opening a menu.

**Comment by alexeymuranov** [comment]
On my laptop i have only one Super key (left).

**Comment by lexruee** [comment]
@alexeymuranov 
I see. On laptops that is really an issue.
