### ISSUE TITLE
Latest version (11) of Arc Menu from extensions.gnome.org results in error when loading

### ISSUE THREAD

**Issue by zakkak** [LinxGem33/Arc-Menu#72]
## What's wrong?

Latest version of Arc Menu from extensions.gnome.org results in error when loading

## What have you tried?

Remove and reinstall. The issue persists.

## Automatically detected errors:

  Error: Schema org.gnome.shell.extensions.zorin-menu could not be found for extension arc-menu@linxgem33.com. Please check your installation.

---

## Version information:

    Shell version: 3.24.2
    Extension version: 11

**Comment by zakkak** [comment]
Seems to work now. Didn't do anything special, just browsing extensions.gnome.org and it suddenly appeared.

**Comment by LinxGem33** [comment]
@zakkak 

glad it managed to resolve itself, extensions.gnome.org can be a bit temperamental sometimes, 

also the Arc menu project is looking for translators to contribute to the project to help translate the menu if you know another language and are willing to contribute 15 minutes it would be appreciated please see #58 for more details.

kind regards
