### ISSUE TITLE
Num keys ENTER for interactive search selection

### ISSUE THREAD

**Issue by itmitica** [LinxGem33/Arc-Menu#77]
Pressing the ENTER key on the numerical block adds a special char to the search box instead of launching the current menu selection.

**Comment by LinxGem33** [comment]
@itmitica 

appreciate the feed back, we will defiantly look into this issue and thank you for bringing this to our attention as this helps us to develop the project and  improve the extension, also could you possibly provide information about:



Information about your distribution. Use the command `lsb_release -a` to retrieve information about your distribution.

- GNOME Shell version. Use the command `gnome-shell --version` to retrieve information about your Shell version.

- Logs from the systemd journal. Use the command `journalctl /usr/bin/gnome-shell -f -o cat` to log the occurrence of the bug.

kind regards

**Comment by itmitica** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

GNOME Shell 3.18.5

**Comment by LinxGem33** [comment]
thank you we will keep you posted of the progress of this issue once we feel we have adequately addressed the issue :smile:

**Comment by itmitica** [comment]
Thank you for Arc menu!

**Comment by LinxGem33** [comment]
your welcome.

**Comment by itmitica** [comment]
So Clutter.Key_KP_Enter is the name of the ENTER on the numeric block on the keyboard.

It should perform the same action as Clutter.KEY_Return.

I tried to add a || in the     // Handle key presses section, but it doesn't do anything.

**Comment by lexruee** [comment]
@itmitica 
Can you checkout the branch `fix-key-kp-enter` from my git repo and report if it fixes your issue?

git repo: https://github.com/lexruee/Arc-Menu/tree/fix-key-kp-enter

**Comment by itmitica** [comment]
@lexruee 
I can confirm it's fixed. Great job!
