### ISSUE TITLE
Filtering is very laggy

### ISSUE THREAD

**Issue by Naatan** [LinxGem33/Arc-Menu#8]
When invoking the menu and then typing an app name to filter down the results render very slowly. It seems to be mostly the first keypress that produces a noticeable lag, once some results are shown further filtering seems much speedier.

I'm guessing the first keystroke causes it to start rendering a large amount of results.

**Comment by LinxGem33** [comment]
@Naatan 

appreciate the feed back, I’ve tested the filtering against the new update which is due on extensions.gnome.org soon and the speed should be improved now so keep an eye out for the new update.

kind regards

**Comment by Naatan** [comment]
Strange, even after a day I still don't have an option to update.

**Comment by LinxGem33** [comment]
@Naatan 

the code has to be reviewed first, it takes about a week depending how many extensions need reviewing.

kind regards

**Comment by Naatan** [comment]
Woah, alright then. I guess I'll wait :)
