### ISSUE TITLE
Impossible to install Arc-Menu

### ISSUE THREAD

**Issue by blackdrum** [LinxGem33/Arc-Menu#81]
Hello 
Could you please tell me the way to install the extension 
I did try to install from the web of extension and also typing in the terminal window and nothing happened

Regards

Everardo

**Comment by LinxGem33** [comment]
@blackdrum 
##
please could you provide us with the following information.
##

- Problem description

- Information about your distribution. Use the command lsb_release -a to retrieve information about your distribution.

- GNOME Shell version. Use the command gnome-shell --version to retrieve information about your Shell version.

- Logs from the systemd journal. Use the command journalctl /usr/bin/gnome-shell -f -o cat to log the occurrence of the bug.
##
kind regards

**Comment by blackdrum** [comment]
Sorry, my problem is the when i try to install the extension  following the instructions in the command line and also the web installer fails.

Distribution 
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

Gnome-Shell
GNOME Shell 3.24.2

Logs

inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fr/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/vi/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/fur/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/sl/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/lv/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/schemas/org.gnome.shell.extensions.arc-menu.gschema.xml
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/id/LC_MESSAGES/zorinmenu.po
  inflating: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/locale/es/LC_MESSAGES/zorinmenu.po
 extracting: /home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/metadata.json
_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed

Thanks for share your time helping me with this.

Everardo

**Comment by LinxGem33** [comment]
@blackdrum 
##
are using Unity or the Gnome desktop?
##
if your using the gnome desktop then remove all traces of the extension then > reboot your system > then install again from [extensions.gnome.org](https://extensions.gnome.org/extension/1228/arc-menu/) > then log out and back in > then activate using gnome tweak tool.
##
report back and let me know if this resolves your issue.
##
kind regards

**Comment by lexruee** [comment]
@LinxGem33 
We should remove these old localization files from the repo.
```
gnome-shell/extensions/arc-menu@linxgem33.com/locale/fr/LC_MESSAGES/zorinmenu...
```
These old files are potential trouble-makers.

**Comment by LinxGem33** [comment]
@lexruee 

its already been done i was doing it as you was leaving a message :+1:

**Comment by blackdrum** [comment]
Now is showing me this

GLib.FileError: Falló al abrir el archivo «/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/schemas/gschemas.compiled»: open() falló: No such file or directory

Stack trace:
  getSettings@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/convenience.js:80:24
  ArcMenuPreferencesWidget<._init@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/prefs.js:51:25
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  buildPrefsWidget@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/prefs.js:521:18
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:49


Sorry I'm new in this

**Comment by lexruee** [comment]
@LinxGem33 
I have the feeling this issue could be related to the problem that @lestcape mentioned here:
https://github.com/LinxGem33/Arc-Menu/issues/32#issuecomment-313891085

I was able to produce an error that prevents the extension to load after the installation. However, this error does not occur frequently.

**Comment by LinxGem33** [comment]
@blackdrum 

are you using Unity desktop?

**Comment by blackdrum** [comment]
@LinxGem33 
No, I'm using Gnome Shell Desktop

**Comment by LinxGem33** [comment]
thank you @blackdrum  , we will keep you posted of the progress of this issue once we feel we have adequately addressed the issue and also if we need further information

**Comment by blackdrum** [comment]
The last thing the i did, was download the zip file,extract the files en the copy  into the extension directory, then i change the **Arc-Menu name** to **arc-menu@linxgem33.com**, with this shows me the extension in the gnome tool, but i can't active the extension and when i click in the options icon,that was the error 

>GLib.FileError: Falló al abrir el archivo «/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/schemas/gschemas.compiled»: open() falló: No such file or directory

>Stack trace:
getSettings@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/convenience.js:80:24
ArcMenuPreferencesWidget<._init@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/prefs.js:51:25
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
buildPrefsWidget@/home/ubuntu/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/prefs.js:521:18
Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5

Thank you @LinxGem33 and @lexruee  for your help

**Comment by LinxGem33** [comment]
@lexruee 

this has happened before with extensions.gnome.org i think its a issue with there content management system.

**Comment by LinxGem33** [comment]
@blackdrum 

you cant do it that way as the schema's are not compiled and need compiling, just remove it and follow 
##
my instructions.

1) extract the zip file and > 
2) right click on the extracted folder > 
3) then choose open in terminal > 
4) in terminal type `make compile`
5) then type `make install`
6) then log out and back in again 
##
then report back
##
kind regards

**Comment by blackdrum** [comment]
@LinxGem33 

I did that you told me, this is whats shows me
![arc-menu error](https://user-images.githubusercontent.com/13478564/28133903-fb544398-6706-11e7-810a-075ab418d4c1.png)

and when i pressed in the option icon, works fine, and shows me the options 
![arc-menu error2](https://user-images.githubusercontent.com/13478564/28133952-24e8e8d0-6707-11e7-8ba9-75b181cfd32b.png)

but i still can't active the extension
![arc-menu error3](https://user-images.githubusercontent.com/13478564/28134003-479df2c6-6707-11e7-8a34-c0a3e704729e.png)

**Comment by lexruee** [comment]
@blackdrum 
Can you try to restart GNOME shell with:
> Alt + F2 and enter the letter: r

**Comment by LinxGem33** [comment]
@blackdrum 

now from the tweak tool click remove
then reboot your system 
then install from [extensions.gnome.org](https://extensions.gnome.org/extension/1228/arc-menu/) 

and then let me know if your able to activate Arc menu

**Comment by blackdrum** [comment]
@LinxGem33 
No, is still happening the same, when i did that you told me, for a short time i can active the extension, but doesn't works, then i reboot, and ones again the extension is inactive

**Comment by LinxGem33** [comment]
@blackdrum 

appreciate you taking the time to test.

last thing to try is load Gnome on a virtual machine and then install the extension if the extension works then you have something on your machine which is conflicting.

kind regards

**Comment by blackdrum** [comment]
@LinxGem33 

I'm testing in a new virtual machine, because this happen also in my pc the same issues

**Comment by LinxGem33** [comment]
@blackdrum 

please refer to this issue #84 as i think this is related to you.

kind regards

**Comment by blackdrum** [comment]
@LinxGem33 

Thank you so much, after install **gir1.2-gmenu-3.0** the extension is working

Regards
