### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by eman1986** [LinxGem33/Arc-Menu#84]
I try to install this and I get the following error:

> GDBus.Error:org.gnome.Shell.LoadExtensionError: Error: Requiring GMenu, version none: Typelib file for namespace 'GMenu' (any version) not found

I don't know what its looking for, hoping someone can help me

**Comment by LinxGem33** [comment]
@eman1986 
appreciate the feed back, also for future issues that you post could you please leave a bit more information about your set-up please refer to the [Reporting bugs](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) in the wiki guide.

could you remove the extension fully and then try install **gir1.2-clutter-1.0** as i don’t think its installed on your system if it is just carry on and reboot and try install the extension again and if you could report back and let me know if this solved your issue.
```
 sudo apt-get install gir1.2-clutter-1.0 
```

kind regards

**Comment by eman1986** [comment]
I had that installed but it lead me to what I didn't have installed which was gir1.2-gmenu-3.0

**Comment by LinxGem33** [comment]
@eman1986 
appreciate you letting me know.

kind regards
