### ISSUE TITLE
Random freeze

### ISSUE THREAD

**Issue by 1Claude** [LinxGem33/Arc-Menu#96]
Hi,

I've been experiencing some random freeze while clicking on the Arc Menu. It won't open and the freeze starts. 

Both on Ubuntu Gnome 17.04 and Fedora 26.

The open Apps become unresponsives. Not the whole desktop. I can open like the Calendar on the panel (Dash to panel) or access the wifi, sound etc. 

I have to reboot.

I don't know where to look to help you more. 

I'm on Fedora 26 right now.

**Comment by LinxGem33** [comment]
@1Claude 

please refer to [Reporting-Bug's](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) on the Arc menu wiki guide.

kind regards

**Comment by 1Claude** [comment]
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 26 (Twenty Six)
Release:	26
Codename:	TwentySix

GNOME Shell 3.24.2

Note : I just rebooted...

journalctl /usr/bin/gnome-shell -f -o cat
Failed to read EDID from 'eDP-1': Aucun fichier ou dossier de ce type
Window manager warning: Failed to set power save mode for output eDP-1: Permission non accordée
Window manager warning: Failed to set power save mode for output eDP-1: Permission non accordée
JS WARNING: [resource:///org/gnome/shell/ui/search.js 259]: reference to undefined property this.provider.canLaunchSearch
_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed
Received error from DBus search provider org.gnome.Calendar.desktop: Gio.IOErrorEnum: Le délai d'attente est dépassé
Ignoring excess values in shadow definition

**Comment by LinxGem33** [comment]
@1Claude 

from the logs i cant see any instance of Arc menu giving any errors i can only conclude you may have something conflicting on your system, try and reinstall the extension and also refer to the wiki in regards to installing etc.

kind regards

**Comment by 1Claude** [comment]
@LinxGem33 

When it will happen again (like once a day) I'll try to report a log, if I can open the Terminal.

**Comment by LinxGem33** [comment]
closed due to lack of response.
