### ISSUE TITLE
Disable hot corner doesn't retain after new session

### ISSUE THREAD

**Issue by AccountOneOff** [LinxGem33/Arc-Menu#97]
I have the option enabled but after logging out the option doesn't stick and I have to disable and enable to get it working.

[Using this release](https://github.com/LinxGem33/Arc-Menu/releases/tag/v13)

https://streamable.com/f8vt9

**Comment by lexruee** [comment]
This issue is probably related to issue https://github.com/LinxGem33/Arc-Menu/issues/95.
In brief: the fix might be to register a signal handler for detecting the change in the session state and to apply the settings again.

**Comment by lexruee** [comment]
@AccountOneOff 
I made a bug fix for this issue on my gtihub repo. Can you checkout the `fix-disable-hotcorner-bug` branch and tell me if it fixes the bug?

my github repo: https://github.com/lexruee/Arc-Menu/tree/fix-disable-hotcorner-bug

**Comment by AccountOneOff** [comment]
Yup that seems to have done it. Thank you! :smiley:

**Comment by lexruee** [comment]
Thanks for testing :smile:.
