### ISSUE TITLE
Latest commit not working with Dash to Panel

### ISSUE THREAD

**Issue by AccountOneOff** [LinxGem33/Arc-Menu#98]
Downloaded latest commit and ran `make uninstall` then `make install` and now Arc Menu doesn't appear unless Dash to Panel is disabled. Curiously enough if DtP is disabled and re-enabled Arc Menu appears but restarting gnome-shell hides it again.

**Comment by LinxGem33** [comment]
@AccountOneOff 

please refer to [Reporting-Bug's](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's) on the Arc menu wiki guide.

kind regards

**Comment by AccountOneOff** [comment]
Oh sorry.

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 17.04
    Release:	17.04
    Codename:	zesty

    GNOME Shell 3.24.2

[journalctl /usr/bin/gnome-shell -f -o cat](https://pastebin.com/VVzCnwFi)

**Comment by lexruee** [comment]
```
parsing error: 35:1:could not recognize next production
JS ERROR: Exception in callback for signal: extension-found: Gio.IOErrorEnum: Error parsing stylesheet 'file:///home/cxf/.local/share/gnome-shell/extensions/arc-menu@linxgem33.com/stylesheet.css'; errcode:15
```

The file stylesheet.css is broken... A right curly brace is missing: https://github.com/LinxGem33/Arc-Menu/blob/master/stylesheet.css#L37
